
void Eprim(int nsource,int ntarget, double *rs,double* js,double* robs, double* Eprimary,int iprec);
void rhsfunc(const int nte,const int np,const  int* te2p,const  double* p,const  double* reg,int nsource, double* rs,double* js, double* rhs,int iprec);
void rhsfunc2nd(const int nte,const int np,const  int* te2p,const  double* p,const  double* reg,int nsource, double *rs,double* js,double* rhs,int iprec);
void rhsfunc3rd(const int nte,const int np,const  int* te2p,const  double* p,const  double* reg,int nsource, double *rs,double* js,double* rhs,int iprec);
void assemblemat(const int nte,const int np,const  int* te2p,const  double* p,const  double* reg,int *crvindex,double* val);
void assemblemat2nd(const int nte,const int np,const  int* te2p,const  double* p,const  double* reg,int *crvindex,double* val);
void assemblemat3rd(const int nte,const int np,const  int* te2p,const  double* p,const  double* reg,int *crvindex,double* val);
#include <uchar.h>
/* --------------------------------------------------- */
/* Automatically generated by mwrap                    */
/* --------------------------------------------------- */

/* Code generated by mwrap */
/*
  Copyright statement for mwrap:

  mwrap -- MEX file generation for MATLAB and Octave
  Copyright (c) 2007-2008 David Bindel

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  You may distribute a work that contains part or all of the source code
  generated by mwrap under the terms of your choice.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/

#include <mex.h>
#include <stdio.h>
#include <string.h>


#ifndef ulong
#  define ulong unsigned long
#endif
#ifndef uint
#  define uint  unsigned int
#endif
#ifndef uchar
#  define uchar unsigned char
#endif


/*
 * Records for call profile.
 */
int* mexprofrecord_= NULL;


/*
 * Support routines for copying data into and out of the MEX stubs
 */

void* mxWrapGetP(const mxArray* a, const char* fmt, const char** e)
{
    void* p = 0;
    mxArray* ap;
    if (mxGetClassID(a) == mxDOUBLE_CLASS && 
        mxGetM(a)*mxGetN(a) == 1 && *mxGetPr(a) == 0)
        return p;
    if (mxIsChar(a)) {
        char pbuf[128];
        mxGetString(a, pbuf, sizeof(pbuf));
        sscanf(pbuf, fmt, &p);
    } 
#ifdef R2008OO
    else if (ap = mxGetProperty(a, 0, "mwptr")) {
        return mxWrapGetP(ap, fmt, e);
    }
#endif
    if (p == 0)
        *e = "Invalid pointer";
    return p;
}

mxArray* mxWrapCreateP(void* p, const char* fmt)
{
    if (p == 0) {
        mxArray* z = mxCreateDoubleMatrix(1,1, mxREAL);
        *mxGetPr(z) = 0;
        return z;
    } else {
        char pbuf[128];
        sprintf(pbuf, fmt, p);
        return mxCreateString(pbuf);
    }
}

mxArray* mxWrapStrncpy(const char* s)
{
    if (s) {
        return mxCreateString(s);
    } else {
        mxArray* z = mxCreateDoubleMatrix(1,1, mxREAL);
        *mxGetPr(z) = 0;
        return z;
    }
}

double mxWrapGetScalar(const mxArray* a, const char** e)
{
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS || mxGetM(a)*mxGetN(a) != 1) {
        *e = "Invalid scalar argument";
        return 0;
    }
    return *mxGetPr(a);
}

char* mxWrapGetString(const mxArray* a, const char** e)
{
    char* s;
    int slen;
    if (!a || (!mxIsChar(a) && mxGetM(a)*mxGetN(a) > 0)) {
        *e = "Invalid string argument";
        return NULL;
    }
    slen = mxGetM(a)*mxGetN(a) + 1;
    s = (char*) mxMalloc(slen);
    if (mxGetM(a)*mxGetN(a) == 0)
        *s = 0;
    else
        mxGetString(a, s, slen);
    return s;
}


#define mxWrapGetArrayDef(func, T) \
T* func(const mxArray* a, const char** e)     \
{ \
    T* array; \
    int arraylen; \
    int i; \
    T* p; \
    double* q; \
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS) { \
        *e = "Invalid array argument"; \
        return 0; \
    } \
    arraylen = mxGetM(a)*mxGetN(a); \
    array = (T*) mxMalloc(mxGetM(a)*mxGetN(a) * sizeof(T)); \
    p = array; \
    q = mxGetPr(a); \
    for (i = 0; i < arraylen; ++i) \
        *p++ = (T) (*q++); \
    return array; \
}


#define mxWrapCopyDef(func, T) \
void func(mxArray* a, const T* q, int n) \
{ \
    int i; \
    double* p = mxGetPr(a); \
    for (i = 0; i < n; ++i) \
        *p++ = *q++; \
}


#define mxWrapReturnDef(func, T) \
mxArray* func(const T* q, int m, int n) \
{ \
    int i; \
    double* p; \
    if (!q) { \
        return mxCreateDoubleMatrix(0,0, mxREAL); \
    } else { \
        mxArray* a = mxCreateDoubleMatrix(m,n, mxREAL); \
        p = mxGetPr(a); \
        for (i = 0; i < m*n; ++i) \
            *p++ = *q++; \
        return a; \
    } \
}


#define mxWrapGetScalarZDef(func, T, ZT, setz) \
void func(T* z, const mxArray* a) \
{ \
    double* pr = mxGetPr(a); \
    double* pi = mxGetPi(a); \
    setz(z, (ZT) *pr, (pi ? (ZT) *pi : (ZT) 0)); \
}


#define mxWrapGetArrayZDef(func, T, ZT, setz) \
T* func(const mxArray* a, const char** e) \
{ \
    T* array; \
    int arraylen; \
    int i; \
    T* p; \
    double* qr; \
    double* qi; \
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS) { \
        *e = "Invalid array argument"; \
        return 0; \
    } \
    arraylen = mxGetM(a)*mxGetN(a); \
    array = (T*) mxMalloc(mxGetM(a)*mxGetN(a) * sizeof(T)); \
    p = array; \
    qr = mxGetPr(a); \
    qi = mxGetPi(a); \
    for (i = 0; i < arraylen; ++i) { \
        ZT val_qr = *qr++; \
        ZT val_qi = (qi ? (ZT) *qi++ : (ZT) 0); \
        setz(p, val_qr, val_qi); \
        ++p; \
    } \
    return array; \
}


#define mxWrapCopyZDef(func, T, real, imag) \
void func(mxArray* a, const T* q, int n) \
{ \
    int i; \
    double* pr = mxGetPr(a); \
    double* pi = mxGetPi(a); \
    for (i = 0; i < n; ++i) { \
        *pr++ = real(*q); \
        *pi++ = imag(*q); \
        ++q; \
    } \
}


#define mxWrapReturnZDef(func, T, real, imag) \
mxArray* func(const T* q, int m, int n) \
{ \
    int i; \
    double* pr; \
    double* pi; \
    if (!q) { \
        return mxCreateDoubleMatrix(0,0, mxCOMPLEX); \
    } else { \
        mxArray* a = mxCreateDoubleMatrix(m,n, mxCOMPLEX); \
        pr = mxGetPr(a); \
        pi = mxGetPi(a); \
        for (i = 0; i < m*n; ++i) { \
            *pr++ = real(*q); \
            *pi++ = imag(*q); \
            ++q; \
        } \
        return a; \
    } \
}

/* Array copier definitions */
mxWrapGetArrayDef(mxWrapGetArray_bool, bool)
mxWrapCopyDef    (mxWrapCopy_bool,     bool)
mxWrapReturnDef  (mxWrapReturn_bool,   bool)
mxWrapGetArrayDef(mxWrapGetArray_char, char)
mxWrapCopyDef    (mxWrapCopy_char,     char)
mxWrapReturnDef  (mxWrapReturn_char,   char)
mxWrapGetArrayDef(mxWrapGetArray_double, double)
mxWrapCopyDef    (mxWrapCopy_double,     double)
mxWrapReturnDef  (mxWrapReturn_double,   double)
mxWrapGetArrayDef(mxWrapGetArray_float, float)
mxWrapCopyDef    (mxWrapCopy_float,     float)
mxWrapReturnDef  (mxWrapReturn_float,   float)
mxWrapGetArrayDef(mxWrapGetArray_int, int)
mxWrapCopyDef    (mxWrapCopy_int,     int)
mxWrapReturnDef  (mxWrapReturn_int,   int)
mxWrapGetArrayDef(mxWrapGetArray_long, long)
mxWrapCopyDef    (mxWrapCopy_long,     long)
mxWrapReturnDef  (mxWrapReturn_long,   long)
mxWrapGetArrayDef(mxWrapGetArray_size_t, size_t)
mxWrapCopyDef    (mxWrapCopy_size_t,     size_t)
mxWrapReturnDef  (mxWrapReturn_size_t,   size_t)
mxWrapGetArrayDef(mxWrapGetArray_uchar, uchar)
mxWrapCopyDef    (mxWrapCopy_uchar,     uchar)
mxWrapReturnDef  (mxWrapReturn_uchar,   uchar)
mxWrapGetArrayDef(mxWrapGetArray_uint, uint)
mxWrapCopyDef    (mxWrapCopy_uint,     uint)
mxWrapReturnDef  (mxWrapReturn_uint,   uint)
mxWrapGetArrayDef(mxWrapGetArray_ulong, ulong)
mxWrapCopyDef    (mxWrapCopy_ulong,     ulong)
mxWrapReturnDef  (mxWrapReturn_ulong,   ulong)

/* ---- demo.mw: 100 ----
 * assemblemat(int nte, int np, int[4, nte] te2p, double[3, np] p, double[nte] reg, inout int[3, nte16] crvindex, inout double[nte16] val);
 */
const char* stubids1_ = "assemblemat(i int, i int, i int[xx], i double[xx], i double[x], io int[xx], io double[x])";

void mexStub1(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int         in0_;    /* nte        */
    int         in1_;    /* np         */
    int*        in2_ =0; /* te2p       */
    double*     in3_ =0; /* p          */
    double*     in4_ =0; /* reg        */
    int*        in5_ =0; /* crvindex   */
    double*     in6_ =0; /* val        */
    int         dim7_;   /* 4          */
    int         dim8_;   /* nte        */
    int         dim9_;   /* 3          */
    int         dim10_;   /* np         */
    int         dim11_;   /* nte        */
    int         dim12_;   /* 3          */
    int         dim13_;   /* nte16      */
    int         dim14_;   /* nte16      */

    dim7_ = (int) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (int) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);

    if (mxGetM(prhs[2]) != dim7_ ||
        mxGetN(prhs[2]) != dim8_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3]) != dim9_ ||
        mxGetN(prhs[3]) != dim10_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim11_) {
        mw_err_txt_ = "Bad argument size: reg";        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim12_ ||
        mxGetN(prhs[5]) != dim13_) {
        mw_err_txt_ = "Bad argument size: crvindex";
        goto mw_err_label;
    }

    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != dim14_) {
        mw_err_txt_ = "Bad argument size: val";        goto mw_err_label;
    }

    in0_ = (int) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in1_ = (int) mxWrapGetScalar(prhs[1], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxGetPr(prhs[4]);
    } else
        in4_ = NULL;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_int(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxWrapGetArray_double(prhs[6], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in6_ = NULL;
    if (mexprofrecord_)
        mexprofrecord_[1]++;
    assemblemat(in0_, in1_, in2_, in3_, in4_, in5_, in6_);
    plhs[0] = mxCreateDoubleMatrix(dim12_, dim13_, mxREAL);
    mxWrapCopy_int(plhs[0], in5_, dim12_*dim13_);
    plhs[1] = mxCreateDoubleMatrix(dim14_, 1, mxREAL);
    mxWrapCopy_double(plhs[1], in6_, dim14_);

mw_err_label:
    if (in2_)  mxFree(in2_);
    if (in5_)  mxFree(in5_);
    if (in6_)  mxFree(in6_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 105 ----
 * assemblemat2nd(int nte, int np, int[10, nte] te2p, double[3, np] p, double[nte] reg, inout int[3, nte100] crvindex, inout double[nte100] val);
 */
const char* stubids2_ = "assemblemat2nd(i int, i int, i int[xx], i double[xx], i double[x], io int[xx], io double[x])";

void mexStub2(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int         in0_;    /* nte        */
    int         in1_;    /* np         */
    int*        in2_ =0; /* te2p       */
    double*     in3_ =0; /* p          */
    double*     in4_ =0; /* reg        */
    int*        in5_ =0; /* crvindex   */
    double*     in6_ =0; /* val        */
    int         dim7_;   /* 10         */
    int         dim8_;   /* nte        */
    int         dim9_;   /* 3          */
    int         dim10_;   /* np         */
    int         dim11_;   /* nte        */
    int         dim12_;   /* 3          */
    int         dim13_;   /* nte100     */
    int         dim14_;   /* nte100     */

    dim7_ = (int) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (int) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);

    if (mxGetM(prhs[2]) != dim7_ ||
        mxGetN(prhs[2]) != dim8_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3]) != dim9_ ||
        mxGetN(prhs[3]) != dim10_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim11_) {
        mw_err_txt_ = "Bad argument size: reg";        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim12_ ||
        mxGetN(prhs[5]) != dim13_) {
        mw_err_txt_ = "Bad argument size: crvindex";
        goto mw_err_label;
    }

    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != dim14_) {
        mw_err_txt_ = "Bad argument size: val";        goto mw_err_label;
    }

    in0_ = (int) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in1_ = (int) mxWrapGetScalar(prhs[1], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxGetPr(prhs[4]);
    } else
        in4_ = NULL;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_int(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxWrapGetArray_double(prhs[6], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in6_ = NULL;
    if (mexprofrecord_)
        mexprofrecord_[2]++;
    assemblemat2nd(in0_, in1_, in2_, in3_, in4_, in5_, in6_);
    plhs[0] = mxCreateDoubleMatrix(dim12_, dim13_, mxREAL);
    mxWrapCopy_int(plhs[0], in5_, dim12_*dim13_);
    plhs[1] = mxCreateDoubleMatrix(dim14_, 1, mxREAL);
    mxWrapCopy_double(plhs[1], in6_, dim14_);

mw_err_label:
    if (in2_)  mxFree(in2_);
    if (in5_)  mxFree(in5_);
    if (in6_)  mxFree(in6_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 110 ----
 * assemblemat3rd(int nte, int np, int[20, nte] te2p, double[3, np] p, double[nte] reg, inout int[3, nte400] crvindex, inout double[nte400] val);
 */
const char* stubids3_ = "assemblemat3rd(i int, i int, i int[xx], i double[xx], i double[x], io int[xx], io double[x])";

void mexStub3(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int         in0_;    /* nte        */
    int         in1_;    /* np         */
    int*        in2_ =0; /* te2p       */
    double*     in3_ =0; /* p          */
    double*     in4_ =0; /* reg        */
    int*        in5_ =0; /* crvindex   */
    double*     in6_ =0; /* val        */
    int         dim7_;   /* 20         */
    int         dim8_;   /* nte        */
    int         dim9_;   /* 3          */
    int         dim10_;   /* np         */
    int         dim11_;   /* nte        */
    int         dim12_;   /* 3          */
    int         dim13_;   /* nte400     */
    int         dim14_;   /* nte400     */

    dim7_ = (int) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (int) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);

    if (mxGetM(prhs[2]) != dim7_ ||
        mxGetN(prhs[2]) != dim8_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3]) != dim9_ ||
        mxGetN(prhs[3]) != dim10_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim11_) {
        mw_err_txt_ = "Bad argument size: reg";        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim12_ ||
        mxGetN(prhs[5]) != dim13_) {
        mw_err_txt_ = "Bad argument size: crvindex";
        goto mw_err_label;
    }

    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != dim14_) {
        mw_err_txt_ = "Bad argument size: val";        goto mw_err_label;
    }

    in0_ = (int) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in1_ = (int) mxWrapGetScalar(prhs[1], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxGetPr(prhs[4]);
    } else
        in4_ = NULL;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_int(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxWrapGetArray_double(prhs[6], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in6_ = NULL;
    if (mexprofrecord_)
        mexprofrecord_[3]++;
    assemblemat3rd(in0_, in1_, in2_, in3_, in4_, in5_, in6_);
    plhs[0] = mxCreateDoubleMatrix(dim12_, dim13_, mxREAL);
    mxWrapCopy_int(plhs[0], in5_, dim12_*dim13_);
    plhs[1] = mxCreateDoubleMatrix(dim14_, 1, mxREAL);
    mxWrapCopy_double(plhs[1], in6_, dim14_);

mw_err_label:
    if (in2_)  mxFree(in2_);
    if (in5_)  mxFree(in5_);
    if (in6_)  mxFree(in6_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 125 ----
 * rhsfunc(int nte, int np, int[4, nte] te2p, double[3, np] p, double[nte] reg, int nsource, double[3, nsource] rs, double[3, nsource] js, inout double[np] rhs, int iprec);
 */
const char* stubids4_ = "rhsfunc(i int, i int, i int[xx], i double[xx], i double[x], i int, i double[xx], i double[xx], io double[x], i int)";

void mexStub4(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int         in0_;    /* nte        */
    int         in1_;    /* np         */
    int*        in2_ =0; /* te2p       */
    double*     in3_ =0; /* p          */
    double*     in4_ =0; /* reg        */
    int         in5_;    /* nsource    */
    double*     in6_ =0; /* rs         */
    double*     in7_ =0; /* js         */
    double*     in8_ =0; /* rhs        */
    int         in9_;    /* iprec      */
    int         dim10_;   /* 4          */
    int         dim11_;   /* nte        */
    int         dim12_;   /* 3          */
    int         dim13_;   /* np         */
    int         dim14_;   /* nte        */
    int         dim15_;   /* 3          */
    int         dim16_;   /* nsource    */
    int         dim17_;   /* 3          */
    int         dim18_;   /* nsource    */
    int         dim19_;   /* np         */

    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (int) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (int) mxWrapGetScalar(prhs[16], &mw_err_txt_);
    dim17_ = (int) mxWrapGetScalar(prhs[17], &mw_err_txt_);
    dim18_ = (int) mxWrapGetScalar(prhs[18], &mw_err_txt_);
    dim19_ = (int) mxWrapGetScalar(prhs[19], &mw_err_txt_);

    if (mxGetM(prhs[2]) != dim10_ ||
        mxGetN(prhs[2]) != dim11_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3]) != dim12_ ||
        mxGetN(prhs[3]) != dim13_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim14_) {
        mw_err_txt_ = "Bad argument size: reg";        goto mw_err_label;
    }

    if (mxGetM(prhs[6]) != dim15_ ||
        mxGetN(prhs[6]) != dim16_) {
        mw_err_txt_ = "Bad argument size: rs";
        goto mw_err_label;
    }

    if (mxGetM(prhs[7]) != dim17_ ||
        mxGetN(prhs[7]) != dim18_) {
        mw_err_txt_ = "Bad argument size: js";
        goto mw_err_label;
    }

    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != dim19_) {
        mw_err_txt_ = "Bad argument size: rhs";        goto mw_err_label;
    }

    in0_ = (int) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in1_ = (int) mxWrapGetScalar(prhs[1], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxGetPr(prhs[4]);
    } else
        in4_ = NULL;
    in5_ = (int) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxGetPr(prhs[6]);
    } else
        in6_ = NULL;
    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != 0) {
        in7_ = mxGetPr(prhs[7]);
    } else
        in7_ = NULL;
    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != 0) {
        in8_ = mxWrapGetArray_double(prhs[8], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in8_ = NULL;
    in9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mexprofrecord_)
        mexprofrecord_[4]++;
    rhsfunc(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, in8_, in9_);
    plhs[0] = mxCreateDoubleMatrix(dim19_, 1, mxREAL);
    mxWrapCopy_double(plhs[0], in8_, dim19_);

mw_err_label:
    if (in2_)  mxFree(in2_);
    if (in8_)  mxFree(in8_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 127 ----
 * rhsfunc2nd(int nte, int np, int[10, nte] te2p, double[3, np] p, double[nte] reg, int nsource, double[3, nsource] rs, double[3, nsource] js, inout double[np] rhs, int iprec);
 */
const char* stubids5_ = "rhsfunc2nd(i int, i int, i int[xx], i double[xx], i double[x], i int, i double[xx], i double[xx], io double[x], i int)";

void mexStub5(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int         in0_;    /* nte        */
    int         in1_;    /* np         */
    int*        in2_ =0; /* te2p       */
    double*     in3_ =0; /* p          */
    double*     in4_ =0; /* reg        */
    int         in5_;    /* nsource    */
    double*     in6_ =0; /* rs         */
    double*     in7_ =0; /* js         */
    double*     in8_ =0; /* rhs        */
    int         in9_;    /* iprec      */
    int         dim10_;   /* 10         */
    int         dim11_;   /* nte        */
    int         dim12_;   /* 3          */
    int         dim13_;   /* np         */
    int         dim14_;   /* nte        */
    int         dim15_;   /* 3          */
    int         dim16_;   /* nsource    */
    int         dim17_;   /* 3          */
    int         dim18_;   /* nsource    */
    int         dim19_;   /* np         */

    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (int) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (int) mxWrapGetScalar(prhs[16], &mw_err_txt_);
    dim17_ = (int) mxWrapGetScalar(prhs[17], &mw_err_txt_);
    dim18_ = (int) mxWrapGetScalar(prhs[18], &mw_err_txt_);
    dim19_ = (int) mxWrapGetScalar(prhs[19], &mw_err_txt_);

    if (mxGetM(prhs[2]) != dim10_ ||
        mxGetN(prhs[2]) != dim11_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3]) != dim12_ ||
        mxGetN(prhs[3]) != dim13_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim14_) {
        mw_err_txt_ = "Bad argument size: reg";        goto mw_err_label;
    }

    if (mxGetM(prhs[6]) != dim15_ ||
        mxGetN(prhs[6]) != dim16_) {
        mw_err_txt_ = "Bad argument size: rs";
        goto mw_err_label;
    }

    if (mxGetM(prhs[7]) != dim17_ ||
        mxGetN(prhs[7]) != dim18_) {
        mw_err_txt_ = "Bad argument size: js";
        goto mw_err_label;
    }

    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != dim19_) {
        mw_err_txt_ = "Bad argument size: rhs";        goto mw_err_label;
    }

    in0_ = (int) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in1_ = (int) mxWrapGetScalar(prhs[1], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxGetPr(prhs[4]);
    } else
        in4_ = NULL;
    in5_ = (int) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxGetPr(prhs[6]);
    } else
        in6_ = NULL;
    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != 0) {
        in7_ = mxGetPr(prhs[7]);
    } else
        in7_ = NULL;
    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != 0) {
        in8_ = mxWrapGetArray_double(prhs[8], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in8_ = NULL;
    in9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mexprofrecord_)
        mexprofrecord_[5]++;
    rhsfunc2nd(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, in8_, in9_);
    plhs[0] = mxCreateDoubleMatrix(dim19_, 1, mxREAL);
    mxWrapCopy_double(plhs[0], in8_, dim19_);

mw_err_label:
    if (in2_)  mxFree(in2_);
    if (in8_)  mxFree(in8_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 129 ----
 * rhsfunc3rd(int nte, int np, int[20, nte] te2p, double[3, np] p, double[nte] reg, int nsource, double[3, nsource] rs, double[3, nsource] js, inout double[np] rhs, int iprec);
 */
const char* stubids6_ = "rhsfunc3rd(i int, i int, i int[xx], i double[xx], i double[x], i int, i double[xx], i double[xx], io double[x], i int)";

void mexStub6(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int         in0_;    /* nte        */
    int         in1_;    /* np         */
    int*        in2_ =0; /* te2p       */
    double*     in3_ =0; /* p          */
    double*     in4_ =0; /* reg        */
    int         in5_;    /* nsource    */
    double*     in6_ =0; /* rs         */
    double*     in7_ =0; /* js         */
    double*     in8_ =0; /* rhs        */
    int         in9_;    /* iprec      */
    int         dim10_;   /* 20         */
    int         dim11_;   /* nte        */
    int         dim12_;   /* 3          */
    int         dim13_;   /* np         */
    int         dim14_;   /* nte        */
    int         dim15_;   /* 3          */
    int         dim16_;   /* nsource    */
    int         dim17_;   /* 3          */
    int         dim18_;   /* nsource    */
    int         dim19_;   /* np         */

    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (int) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (int) mxWrapGetScalar(prhs[16], &mw_err_txt_);
    dim17_ = (int) mxWrapGetScalar(prhs[17], &mw_err_txt_);
    dim18_ = (int) mxWrapGetScalar(prhs[18], &mw_err_txt_);
    dim19_ = (int) mxWrapGetScalar(prhs[19], &mw_err_txt_);

    if (mxGetM(prhs[2]) != dim10_ ||
        mxGetN(prhs[2]) != dim11_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3]) != dim12_ ||
        mxGetN(prhs[3]) != dim13_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim14_) {
        mw_err_txt_ = "Bad argument size: reg";        goto mw_err_label;
    }

    if (mxGetM(prhs[6]) != dim15_ ||
        mxGetN(prhs[6]) != dim16_) {
        mw_err_txt_ = "Bad argument size: rs";
        goto mw_err_label;
    }

    if (mxGetM(prhs[7]) != dim17_ ||
        mxGetN(prhs[7]) != dim18_) {
        mw_err_txt_ = "Bad argument size: js";
        goto mw_err_label;
    }

    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != dim19_) {
        mw_err_txt_ = "Bad argument size: rhs";        goto mw_err_label;
    }

    in0_ = (int) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in1_ = (int) mxWrapGetScalar(prhs[1], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxGetPr(prhs[4]);
    } else
        in4_ = NULL;
    in5_ = (int) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxGetPr(prhs[6]);
    } else
        in6_ = NULL;
    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != 0) {
        in7_ = mxGetPr(prhs[7]);
    } else
        in7_ = NULL;
    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != 0) {
        in8_ = mxWrapGetArray_double(prhs[8], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in8_ = NULL;
    in9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mexprofrecord_)
        mexprofrecord_[6]++;
    rhsfunc3rd(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, in8_, in9_);
    plhs[0] = mxCreateDoubleMatrix(dim19_, 1, mxREAL);
    mxWrapCopy_double(plhs[0], in8_, dim19_);

mw_err_label:
    if (in2_)  mxFree(in2_);
    if (in8_)  mxFree(in8_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 136 ----
 * Eprim(int nsource, int ntarget, double[3, nsource] rs, double[3, nsource] js, double[3, ntarget] robs, inout double[3, ntarget] Eout, int iprecEp);
 */
const char* stubids7_ = "Eprim(i int, i int, i double[xx], i double[xx], i double[xx], io double[xx], i int)";

void mexStub7(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int         in0_;    /* nsource    */
    int         in1_;    /* ntarget    */
    double*     in2_ =0; /* rs         */
    double*     in3_ =0; /* js         */
    double*     in4_ =0; /* robs       */
    double*     in5_ =0; /* Eout       */
    int         in6_;    /* iprecEp    */
    int         dim7_;   /* 3          */
    int         dim8_;   /* nsource    */
    int         dim9_;   /* 3          */
    int         dim10_;   /* nsource    */
    int         dim11_;   /* 3          */
    int         dim12_;   /* ntarget    */
    int         dim13_;   /* 3          */
    int         dim14_;   /* ntarget    */

    dim7_ = (int) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (int) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);

    if (mxGetM(prhs[2]) != dim7_ ||
        mxGetN(prhs[2]) != dim8_) {
        mw_err_txt_ = "Bad argument size: rs";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3]) != dim9_ ||
        mxGetN(prhs[3]) != dim10_) {
        mw_err_txt_ = "Bad argument size: js";
        goto mw_err_label;
    }

    if (mxGetM(prhs[4]) != dim11_ ||
        mxGetN(prhs[4]) != dim12_) {
        mw_err_txt_ = "Bad argument size: robs";
        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim13_ ||
        mxGetN(prhs[5]) != dim14_) {
        mw_err_txt_ = "Bad argument size: Eout";
        goto mw_err_label;
    }

    in0_ = (int) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in1_ = (int) mxWrapGetScalar(prhs[1], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxGetPr(prhs[4]);
    } else
        in4_ = NULL;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_double(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;
    in6_ = (int) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mexprofrecord_)
        mexprofrecord_[7]++;
    Eprim(in0_, in1_, in2_, in3_, in4_, in5_, in6_);
    plhs[0] = mxCreateDoubleMatrix(dim13_, dim14_, mxREAL);
    mxWrapCopy_double(plhs[0], in5_, dim13_*dim14_);

mw_err_label:
    if (in5_)  mxFree(in5_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ----
 */
void mexFunction(int nlhs, mxArray* plhs[],
                 int nrhs, const mxArray* prhs[])
{
    char id[512];
    if (nrhs == 0) {
        mexPrintf("Mex function installed\n");
        return;
    }

    if (mxGetString(prhs[0], id, sizeof(id)) != 0)
        mexErrMsgTxt("Identifier should be a string");
    else if (strcmp(id, stubids1_) == 0)
        mexStub1(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids2_) == 0)
        mexStub2(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids3_) == 0)
        mexStub3(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids4_) == 0)
        mexStub4(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids5_) == 0)
        mexStub5(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids6_) == 0)
        mexStub6(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids7_) == 0)
        mexStub7(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, "*profile on*") == 0) {
        if (!mexprofrecord_) {
            mexprofrecord_ = (int*) malloc(8 * sizeof(int));
            mexLock();
        }
        memset(mexprofrecord_, 0, 8 * sizeof(int));
    } else if (strcmp(id, "*profile off*") == 0) {
        if (mexprofrecord_) {
            free(mexprofrecord_);
            mexUnlock();
        }
        mexprofrecord_ = NULL;
    } else if (strcmp(id, "*profile report*") == 0) {
        if (!mexprofrecord_)
            mexPrintf("Profiler inactive\n");
        mexPrintf("%d calls to demo.mw:100\n", mexprofrecord_[1]);
        mexPrintf("%d calls to demo.mw:105\n", mexprofrecord_[2]);
        mexPrintf("%d calls to demo.mw:110\n", mexprofrecord_[3]);
        mexPrintf("%d calls to demo.mw:125\n", mexprofrecord_[4]);
        mexPrintf("%d calls to demo.mw:127\n", mexprofrecord_[5]);
        mexPrintf("%d calls to demo.mw:129\n", mexprofrecord_[6]);
        mexPrintf("%d calls to demo.mw:136\n", mexprofrecord_[7]);
    } else if (strcmp(id, "*profile log*") == 0) {
        FILE* logfp;
        if (nrhs != 2 || mxGetString(prhs[1], id, sizeof(id)) != 0)
            mexErrMsgTxt("Must have two string arguments");
        logfp = fopen(id, "w+");
        if (!logfp)
            mexErrMsgTxt("Cannot open log for output");
        if (!mexprofrecord_)
            fprintf(logfp, "Profiler inactive\n");
        fprintf(logfp, "%d calls to demo.mw:100\n", mexprofrecord_[1]);
        fprintf(logfp, "%d calls to demo.mw:105\n", mexprofrecord_[2]);
        fprintf(logfp, "%d calls to demo.mw:110\n", mexprofrecord_[3]);
        fprintf(logfp, "%d calls to demo.mw:125\n", mexprofrecord_[4]);
        fprintf(logfp, "%d calls to demo.mw:127\n", mexprofrecord_[5]);
        fprintf(logfp, "%d calls to demo.mw:129\n", mexprofrecord_[6]);
        fprintf(logfp, "%d calls to demo.mw:136\n", mexprofrecord_[7]);
        fclose(logfp);
    } else
        mexErrMsgTxt("Unknown identifier");
}

