
void Eprim(int nsource,int ntarget, double *rs,double* js,double* robs, double* Eprimary,int iprec);
void rhsfunc(const int nte,const int np,const  int* te2p,const  double* p,const  double* reg,int nsource, double* rs,double* js, double* rhs,int iprec);
void rhsfunc2nd(const int nte,const int np,const  int* te2p,const  double* p,const  double* reg,int nsource, double *rs,double* js,double* rhs,int iprec);
void rhsfunc3rd(const int nte,const int np,const  int* te2p,const  double* p,const  double* reg,int nsource, double *rs,double* js,double* rhs,int iprec);
void assemblemat(const int nte,const int np,const  int* te2p,const  double* p,const  double* reg,int *crvindex,double* val);
void assemblemat2nd(const int nte,const int np,const  int* te2p,const  double* p,const  double* reg,int *crvindex,double* val);
void assemblemat3rd(const int nte,const int np,const  int* te2p,const  double* p,const  double* reg,int *crvindex,double* val);
void pointLocation_f(const  double* robs,const  int nobs,const  int* te2p,const  int nte,const double* p
  ,const int te_stride,const int* te2te,  int* teid, double* bari);
void totalEfield(const  double* robs,const  int nobs,const int* te2te,const  int* te2p,const  int nte,const double* p
  ,const  double* rs,const  double* js,const  int nsource,const double* u,  double* soln,const int iprec);
void totalEfield2nd(const  double* robs,const  int nobs,const int* te2te,const  int* te2p,const  int nte,const double* p
  ,const  double* rs,const  double* js,const  int nsource,const double* u,  double* soln,const int iprec);
void totalEfield3rd(const  double* robs,const  int nobs,const int* te2te,const  int* te2p,const  int nte,const double* p
  ,const  double* rs,const  double* js,const  int nsource,const double* u,  double* soln,const int iprec);
void generatemesh3rd(const int nte,const  int* te2p,const double* p,const int np,const int ne,int* te2p2,double* p2);
void generatemesh2nd(const int nte,const  int* te2p,const double* p,const int np,int* te2p2,double* p2);
int generateedge_ct(const int nte,const  int* te2p);
int generateface_ct(const int nte,const  int* te2p);

void generatetetrapaths(const int nte,const  int* te2p,int* te2te);
#include <uchar.h>
/* --------------------------------------------------- */
/* Automatically generated by mwrap                    */
/* --------------------------------------------------- */

/* Code generated by mwrap */
/*
  Copyright statement for mwrap:

  mwrap -- MEX file generation for MATLAB and Octave
  Copyright (c) 2007-2008 David Bindel

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  You may distribute a work that contains part or all of the source code
  generated by mwrap under the terms of your choice.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/

#include <mex.h>
#include <stdio.h>
#include <string.h>


#ifndef ulong
#  define ulong unsigned long
#endif
#ifndef uint
#  define uint  unsigned int
#endif
#ifndef uchar
#  define uchar unsigned char
#endif


/*
 * Records for call profile.
 */
int* mexprofrecord_= NULL;


/*
 * Support routines for copying data into and out of the MEX stubs
 */

void* mxWrapGetP(const mxArray* a, const char* fmt, const char** e)
{
    void* p = 0;
    mxArray* ap;
    if (mxGetClassID(a) == mxDOUBLE_CLASS && 
        mxGetM(a)*mxGetN(a) == 1 && *mxGetPr(a) == 0)
        return p;
    if (mxIsChar(a)) {
        char pbuf[128];
        mxGetString(a, pbuf, sizeof(pbuf));
        sscanf(pbuf, fmt, &p);
    } 
#ifdef R2008OO
    else if (ap = mxGetProperty(a, 0, "mwptr")) {
        return mxWrapGetP(ap, fmt, e);
    }
#endif
    if (p == 0)
        *e = "Invalid pointer";
    return p;
}

mxArray* mxWrapCreateP(void* p, const char* fmt)
{
    if (p == 0) {
        mxArray* z = mxCreateDoubleMatrix(1,1, mxREAL);
        *mxGetPr(z) = 0;
        return z;
    } else {
        char pbuf[128];
        sprintf(pbuf, fmt, p);
        return mxCreateString(pbuf);
    }
}

mxArray* mxWrapStrncpy(const char* s)
{
    if (s) {
        return mxCreateString(s);
    } else {
        mxArray* z = mxCreateDoubleMatrix(1,1, mxREAL);
        *mxGetPr(z) = 0;
        return z;
    }
}

double mxWrapGetScalar(const mxArray* a, const char** e)
{
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS || mxGetM(a)*mxGetN(a) != 1) {
        *e = "Invalid scalar argument";
        return 0;
    }
    return *mxGetPr(a);
}

char* mxWrapGetString(const mxArray* a, const char** e)
{
    char* s;
    int slen;
    if (!a || (!mxIsChar(a) && mxGetM(a)*mxGetN(a) > 0)) {
        *e = "Invalid string argument";
        return NULL;
    }
    slen = mxGetM(a)*mxGetN(a) + 1;
    s = (char*) mxMalloc(slen);
    if (mxGetM(a)*mxGetN(a) == 0)
        *s = 0;
    else
        mxGetString(a, s, slen);
    return s;
}


#define mxWrapGetArrayDef(func, T) \
T* func(const mxArray* a, const char** e)     \
{ \
    T* array; \
    int arraylen; \
    int i; \
    T* p; \
    double* q; \
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS) { \
        *e = "Invalid array argument"; \
        return 0; \
    } \
    arraylen = mxGetM(a)*mxGetN(a); \
    array = (T*) mxMalloc(mxGetM(a)*mxGetN(a) * sizeof(T)); \
    p = array; \
    q = mxGetPr(a); \
    for (i = 0; i < arraylen; ++i) \
        *p++ = (T) (*q++); \
    return array; \
}


#define mxWrapCopyDef(func, T) \
void func(mxArray* a, const T* q, int n) \
{ \
    int i; \
    double* p = mxGetPr(a); \
    for (i = 0; i < n; ++i) \
        *p++ = *q++; \
}


#define mxWrapReturnDef(func, T) \
mxArray* func(const T* q, int m, int n) \
{ \
    int i; \
    double* p; \
    if (!q) { \
        return mxCreateDoubleMatrix(0,0, mxREAL); \
    } else { \
        mxArray* a = mxCreateDoubleMatrix(m,n, mxREAL); \
        p = mxGetPr(a); \
        for (i = 0; i < m*n; ++i) \
            *p++ = *q++; \
        return a; \
    } \
}


#define mxWrapGetScalarZDef(func, T, ZT, setz) \
void func(T* z, const mxArray* a) \
{ \
    double* pr = mxGetPr(a); \
    double* pi = mxGetPi(a); \
    setz(z, (ZT) *pr, (pi ? (ZT) *pi : (ZT) 0)); \
}


#define mxWrapGetArrayZDef(func, T, ZT, setz) \
T* func(const mxArray* a, const char** e) \
{ \
    T* array; \
    int arraylen; \
    int i; \
    T* p; \
    double* qr; \
    double* qi; \
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS) { \
        *e = "Invalid array argument"; \
        return 0; \
    } \
    arraylen = mxGetM(a)*mxGetN(a); \
    array = (T*) mxMalloc(mxGetM(a)*mxGetN(a) * sizeof(T)); \
    p = array; \
    qr = mxGetPr(a); \
    qi = mxGetPi(a); \
    for (i = 0; i < arraylen; ++i) { \
        ZT val_qr = *qr++; \
        ZT val_qi = (qi ? (ZT) *qi++ : (ZT) 0); \
        setz(p, val_qr, val_qi); \
        ++p; \
    } \
    return array; \
}


#define mxWrapCopyZDef(func, T, real, imag) \
void func(mxArray* a, const T* q, int n) \
{ \
    int i; \
    double* pr = mxGetPr(a); \
    double* pi = mxGetPi(a); \
    for (i = 0; i < n; ++i) { \
        *pr++ = real(*q); \
        *pi++ = imag(*q); \
        ++q; \
    } \
}


#define mxWrapReturnZDef(func, T, real, imag) \
mxArray* func(const T* q, int m, int n) \
{ \
    int i; \
    double* pr; \
    double* pi; \
    if (!q) { \
        return mxCreateDoubleMatrix(0,0, mxCOMPLEX); \
    } else { \
        mxArray* a = mxCreateDoubleMatrix(m,n, mxCOMPLEX); \
        pr = mxGetPr(a); \
        pi = mxGetPi(a); \
        for (i = 0; i < m*n; ++i) { \
            *pr++ = real(*q); \
            *pi++ = imag(*q); \
            ++q; \
        } \
        return a; \
    } \
}

/* Array copier definitions */
mxWrapGetArrayDef(mxWrapGetArray_bool, bool)
mxWrapCopyDef    (mxWrapCopy_bool,     bool)
mxWrapReturnDef  (mxWrapReturn_bool,   bool)
mxWrapGetArrayDef(mxWrapGetArray_char, char)
mxWrapCopyDef    (mxWrapCopy_char,     char)
mxWrapReturnDef  (mxWrapReturn_char,   char)
mxWrapGetArrayDef(mxWrapGetArray_double, double)
mxWrapCopyDef    (mxWrapCopy_double,     double)
mxWrapReturnDef  (mxWrapReturn_double,   double)
mxWrapGetArrayDef(mxWrapGetArray_float, float)
mxWrapCopyDef    (mxWrapCopy_float,     float)
mxWrapReturnDef  (mxWrapReturn_float,   float)
mxWrapGetArrayDef(mxWrapGetArray_int, int)
mxWrapCopyDef    (mxWrapCopy_int,     int)
mxWrapReturnDef  (mxWrapReturn_int,   int)
mxWrapGetArrayDef(mxWrapGetArray_long, long)
mxWrapCopyDef    (mxWrapCopy_long,     long)
mxWrapReturnDef  (mxWrapReturn_long,   long)
mxWrapGetArrayDef(mxWrapGetArray_size_t, size_t)
mxWrapCopyDef    (mxWrapCopy_size_t,     size_t)
mxWrapReturnDef  (mxWrapReturn_size_t,   size_t)
mxWrapGetArrayDef(mxWrapGetArray_uchar, uchar)
mxWrapCopyDef    (mxWrapCopy_uchar,     uchar)
mxWrapReturnDef  (mxWrapReturn_uchar,   uchar)
mxWrapGetArrayDef(mxWrapGetArray_uint, uint)
mxWrapCopyDef    (mxWrapCopy_uint,     uint)
mxWrapReturnDef  (mxWrapReturn_uint,   uint)
mxWrapGetArrayDef(mxWrapGetArray_ulong, ulong)
mxWrapCopyDef    (mxWrapCopy_ulong,     ulong)
mxWrapReturnDef  (mxWrapReturn_ulong,   ulong)

/* ---- demo.mw: 75 ----
 * int ne = generateedge_ct(int nte, int[4, nte] te2p);
 */
const char* stubids1_ = "o int = generateedge_ct(i int, i int[xx])";

void mexStub1(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int         in0_;    /* nte        */
    int*        in1_ =0; /* te2p       */
    int         out0_;   /* ne         */
    int         dim2_;   /* 4          */
    int         dim3_;   /* nte        */

    dim2_ = (int) mxWrapGetScalar(prhs[2], &mw_err_txt_);
    dim3_ = (int) mxWrapGetScalar(prhs[3], &mw_err_txt_);

    if (mxGetM(prhs[1]) != dim2_ ||
        mxGetN(prhs[1]) != dim3_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    in0_ = (int) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;
    if (mexprofrecord_)
        mexprofrecord_[1]++;
    out0_ = generateedge_ct(in0_, in1_);
    plhs[0] = mxCreateDoubleMatrix(1, 1, mxREAL);
    *mxGetPr(plhs[0]) = out0_;

mw_err_label:
    if (in1_)  mxFree(in1_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 78 ----
 * generatemesh2nd(int nte, int[4, nte] te2p, double[3, np] p, int np, inout int[10, nte] te2p2, inout double[3, npne] p2);
 */
const char* stubids2_ = "generatemesh2nd(i int, i int[xx], i double[xx], i int, io int[xx], io double[xx])";

void mexStub2(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int         in0_;    /* nte        */
    int*        in1_ =0; /* te2p       */
    double*     in2_ =0; /* p          */
    int         in3_;    /* np         */
    int*        in4_ =0; /* te2p2      */
    double*     in5_ =0; /* p2         */
    int         dim6_;   /* 4          */
    int         dim7_;   /* nte        */
    int         dim8_;   /* 3          */
    int         dim9_;   /* np         */
    int         dim10_;   /* 10         */
    int         dim11_;   /* nte        */
    int         dim12_;   /* 3          */
    int         dim13_;   /* npne       */

    dim6_ = (int) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    dim7_ = (int) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (int) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);

    if (mxGetM(prhs[1]) != dim6_ ||
        mxGetN(prhs[1]) != dim7_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[2]) != dim8_ ||
        mxGetN(prhs[2]) != dim9_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[4]) != dim10_ ||
        mxGetN(prhs[4]) != dim11_) {
        mw_err_txt_ = "Bad argument size: te2p2";
        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim12_ ||
        mxGetN(prhs[5]) != dim13_) {
        mw_err_txt_ = "Bad argument size: p2";
        goto mw_err_label;
    }

    in0_ = (int) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    in3_ = (int) mxWrapGetScalar(prhs[3], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxWrapGetArray_int(prhs[4], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in4_ = NULL;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_double(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;
    if (mexprofrecord_)
        mexprofrecord_[2]++;
    generatemesh2nd(in0_, in1_, in2_, in3_, in4_, in5_);
    plhs[0] = mxCreateDoubleMatrix(dim10_, dim11_, mxREAL);
    mxWrapCopy_int(plhs[0], in4_, dim10_*dim11_);
    plhs[1] = mxCreateDoubleMatrix(dim12_, dim13_, mxREAL);
    mxWrapCopy_double(plhs[1], in5_, dim12_*dim13_);

mw_err_label:
    if (in1_)  mxFree(in1_);
    if (in4_)  mxFree(in4_);
    if (in5_)  mxFree(in5_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 80 ----
 * int ne = generateedge_ct(int nte, int[4, nte] te2p);
 */
const char* stubids3_ = "o int = generateedge_ct(i int, i int[xx])";

void mexStub3(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int         in0_;    /* nte        */
    int*        in1_ =0; /* te2p       */
    int         out0_;   /* ne         */
    int         dim2_;   /* 4          */
    int         dim3_;   /* nte        */

    dim2_ = (int) mxWrapGetScalar(prhs[2], &mw_err_txt_);
    dim3_ = (int) mxWrapGetScalar(prhs[3], &mw_err_txt_);

    if (mxGetM(prhs[1]) != dim2_ ||
        mxGetN(prhs[1]) != dim3_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    in0_ = (int) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;
    if (mexprofrecord_)
        mexprofrecord_[3]++;
    out0_ = generateedge_ct(in0_, in1_);
    plhs[0] = mxCreateDoubleMatrix(1, 1, mxREAL);
    *mxGetPr(plhs[0]) = out0_;

mw_err_label:
    if (in1_)  mxFree(in1_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 81 ----
 * int nf = generateface_ct(int nte, int[4, nte] te2p);
 */
const char* stubids4_ = "o int = generateface_ct(i int, i int[xx])";

void mexStub4(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int         in0_;    /* nte        */
    int*        in1_ =0; /* te2p       */
    int         out0_;   /* nf         */
    int         dim2_;   /* 4          */
    int         dim3_;   /* nte        */

    dim2_ = (int) mxWrapGetScalar(prhs[2], &mw_err_txt_);
    dim3_ = (int) mxWrapGetScalar(prhs[3], &mw_err_txt_);

    if (mxGetM(prhs[1]) != dim2_ ||
        mxGetN(prhs[1]) != dim3_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    in0_ = (int) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;
    if (mexprofrecord_)
        mexprofrecord_[4]++;
    out0_ = generateface_ct(in0_, in1_);
    plhs[0] = mxCreateDoubleMatrix(1, 1, mxREAL);
    *mxGetPr(plhs[0]) = out0_;

mw_err_label:
    if (in1_)  mxFree(in1_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 84 ----
 * generatemesh3rd(int nte, int[4, nte] te2p, double[3, np] p, int np, int ne, inout int[20, nte] te2p2, inout double[3, npne] p2);
 */
const char* stubids5_ = "generatemesh3rd(i int, i int[xx], i double[xx], i int, i int, io int[xx], io double[xx])";

void mexStub5(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int         in0_;    /* nte        */
    int*        in1_ =0; /* te2p       */
    double*     in2_ =0; /* p          */
    int         in3_;    /* np         */
    int         in4_;    /* ne         */
    int*        in5_ =0; /* te2p2      */
    double*     in6_ =0; /* p2         */
    int         dim7_;   /* 4          */
    int         dim8_;   /* nte        */
    int         dim9_;   /* 3          */
    int         dim10_;   /* np         */
    int         dim11_;   /* 20         */
    int         dim12_;   /* nte        */
    int         dim13_;   /* 3          */
    int         dim14_;   /* npne       */

    dim7_ = (int) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (int) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);

    if (mxGetM(prhs[1]) != dim7_ ||
        mxGetN(prhs[1]) != dim8_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[2]) != dim9_ ||
        mxGetN(prhs[2]) != dim10_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim11_ ||
        mxGetN(prhs[5]) != dim12_) {
        mw_err_txt_ = "Bad argument size: te2p2";
        goto mw_err_label;
    }

    if (mxGetM(prhs[6]) != dim13_ ||
        mxGetN(prhs[6]) != dim14_) {
        mw_err_txt_ = "Bad argument size: p2";
        goto mw_err_label;
    }

    in0_ = (int) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    in3_ = (int) mxWrapGetScalar(prhs[3], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in4_ = (int) mxWrapGetScalar(prhs[4], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_int(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxWrapGetArray_double(prhs[6], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in6_ = NULL;
    if (mexprofrecord_)
        mexprofrecord_[5]++;
    generatemesh3rd(in0_, in1_, in2_, in3_, in4_, in5_, in6_);
    plhs[0] = mxCreateDoubleMatrix(dim11_, dim12_, mxREAL);
    mxWrapCopy_int(plhs[0], in5_, dim11_*dim12_);
    plhs[1] = mxCreateDoubleMatrix(dim13_, dim14_, mxREAL);
    mxWrapCopy_double(plhs[1], in6_, dim13_*dim14_);

mw_err_label:
    if (in1_)  mxFree(in1_);
    if (in5_)  mxFree(in5_);
    if (in6_)  mxFree(in6_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 95 ----
 * assemblemat(int nte, int np, int[4, nte] te2p, double[3, np] p, double[nte] reg, inout int[3, nte16] crvindex, inout double[nte16] val);
 */
const char* stubids6_ = "assemblemat(i int, i int, i int[xx], i double[xx], i double[x], io int[xx], io double[x])";

void mexStub6(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int         in0_;    /* nte        */
    int         in1_;    /* np         */
    int*        in2_ =0; /* te2p       */
    double*     in3_ =0; /* p          */
    double*     in4_ =0; /* reg        */
    int*        in5_ =0; /* crvindex   */
    double*     in6_ =0; /* val        */
    int         dim7_;   /* 4          */
    int         dim8_;   /* nte        */
    int         dim9_;   /* 3          */
    int         dim10_;   /* np         */
    int         dim11_;   /* nte        */
    int         dim12_;   /* 3          */
    int         dim13_;   /* nte16      */
    int         dim14_;   /* nte16      */

    dim7_ = (int) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (int) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);

    if (mxGetM(prhs[2]) != dim7_ ||
        mxGetN(prhs[2]) != dim8_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3]) != dim9_ ||
        mxGetN(prhs[3]) != dim10_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim11_) {
        mw_err_txt_ = "Bad argument size: reg";        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim12_ ||
        mxGetN(prhs[5]) != dim13_) {
        mw_err_txt_ = "Bad argument size: crvindex";
        goto mw_err_label;
    }

    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != dim14_) {
        mw_err_txt_ = "Bad argument size: val";        goto mw_err_label;
    }

    in0_ = (int) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in1_ = (int) mxWrapGetScalar(prhs[1], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxGetPr(prhs[4]);
    } else
        in4_ = NULL;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_int(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxWrapGetArray_double(prhs[6], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in6_ = NULL;
    if (mexprofrecord_)
        mexprofrecord_[6]++;
    assemblemat(in0_, in1_, in2_, in3_, in4_, in5_, in6_);
    plhs[0] = mxCreateDoubleMatrix(dim12_, dim13_, mxREAL);
    mxWrapCopy_int(plhs[0], in5_, dim12_*dim13_);
    plhs[1] = mxCreateDoubleMatrix(dim14_, 1, mxREAL);
    mxWrapCopy_double(plhs[1], in6_, dim14_);

mw_err_label:
    if (in2_)  mxFree(in2_);
    if (in5_)  mxFree(in5_);
    if (in6_)  mxFree(in6_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 100 ----
 * assemblemat2nd(int nte, int np, int[10, nte] te2p, double[3, np] p, double[nte] reg, inout int[3, nte100] crvindex, inout double[nte100] val);
 */
const char* stubids7_ = "assemblemat2nd(i int, i int, i int[xx], i double[xx], i double[x], io int[xx], io double[x])";

void mexStub7(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int         in0_;    /* nte        */
    int         in1_;    /* np         */
    int*        in2_ =0; /* te2p       */
    double*     in3_ =0; /* p          */
    double*     in4_ =0; /* reg        */
    int*        in5_ =0; /* crvindex   */
    double*     in6_ =0; /* val        */
    int         dim7_;   /* 10         */
    int         dim8_;   /* nte        */
    int         dim9_;   /* 3          */
    int         dim10_;   /* np         */
    int         dim11_;   /* nte        */
    int         dim12_;   /* 3          */
    int         dim13_;   /* nte100     */
    int         dim14_;   /* nte100     */

    dim7_ = (int) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (int) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);

    if (mxGetM(prhs[2]) != dim7_ ||
        mxGetN(prhs[2]) != dim8_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3]) != dim9_ ||
        mxGetN(prhs[3]) != dim10_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim11_) {
        mw_err_txt_ = "Bad argument size: reg";        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim12_ ||
        mxGetN(prhs[5]) != dim13_) {
        mw_err_txt_ = "Bad argument size: crvindex";
        goto mw_err_label;
    }

    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != dim14_) {
        mw_err_txt_ = "Bad argument size: val";        goto mw_err_label;
    }

    in0_ = (int) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in1_ = (int) mxWrapGetScalar(prhs[1], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxGetPr(prhs[4]);
    } else
        in4_ = NULL;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_int(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxWrapGetArray_double(prhs[6], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in6_ = NULL;
    if (mexprofrecord_)
        mexprofrecord_[7]++;
    assemblemat2nd(in0_, in1_, in2_, in3_, in4_, in5_, in6_);
    plhs[0] = mxCreateDoubleMatrix(dim12_, dim13_, mxREAL);
    mxWrapCopy_int(plhs[0], in5_, dim12_*dim13_);
    plhs[1] = mxCreateDoubleMatrix(dim14_, 1, mxREAL);
    mxWrapCopy_double(plhs[1], in6_, dim14_);

mw_err_label:
    if (in2_)  mxFree(in2_);
    if (in5_)  mxFree(in5_);
    if (in6_)  mxFree(in6_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 105 ----
 * assemblemat3rd(int nte, int np, int[20, nte] te2p, double[3, np] p, double[nte] reg, inout int[3, nte400] crvindex, inout double[nte400] val);
 */
const char* stubids8_ = "assemblemat3rd(i int, i int, i int[xx], i double[xx], i double[x], io int[xx], io double[x])";

void mexStub8(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int         in0_;    /* nte        */
    int         in1_;    /* np         */
    int*        in2_ =0; /* te2p       */
    double*     in3_ =0; /* p          */
    double*     in4_ =0; /* reg        */
    int*        in5_ =0; /* crvindex   */
    double*     in6_ =0; /* val        */
    int         dim7_;   /* 20         */
    int         dim8_;   /* nte        */
    int         dim9_;   /* 3          */
    int         dim10_;   /* np         */
    int         dim11_;   /* nte        */
    int         dim12_;   /* 3          */
    int         dim13_;   /* nte400     */
    int         dim14_;   /* nte400     */

    dim7_ = (int) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (int) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);

    if (mxGetM(prhs[2]) != dim7_ ||
        mxGetN(prhs[2]) != dim8_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3]) != dim9_ ||
        mxGetN(prhs[3]) != dim10_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim11_) {
        mw_err_txt_ = "Bad argument size: reg";        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim12_ ||
        mxGetN(prhs[5]) != dim13_) {
        mw_err_txt_ = "Bad argument size: crvindex";
        goto mw_err_label;
    }

    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != dim14_) {
        mw_err_txt_ = "Bad argument size: val";        goto mw_err_label;
    }

    in0_ = (int) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in1_ = (int) mxWrapGetScalar(prhs[1], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxGetPr(prhs[4]);
    } else
        in4_ = NULL;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_int(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxWrapGetArray_double(prhs[6], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in6_ = NULL;
    if (mexprofrecord_)
        mexprofrecord_[8]++;
    assemblemat3rd(in0_, in1_, in2_, in3_, in4_, in5_, in6_);
    plhs[0] = mxCreateDoubleMatrix(dim12_, dim13_, mxREAL);
    mxWrapCopy_int(plhs[0], in5_, dim12_*dim13_);
    plhs[1] = mxCreateDoubleMatrix(dim14_, 1, mxREAL);
    mxWrapCopy_double(plhs[1], in6_, dim14_);

mw_err_label:
    if (in2_)  mxFree(in2_);
    if (in5_)  mxFree(in5_);
    if (in6_)  mxFree(in6_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 119 ----
 * rhsfunc(int nte, int np, int[4, nte] te2p, double[3, np] p, double[nte] reg, int nsource, double[3, nsource] rs, double[3, nsource] js, inout double[np] rhs, int iprec);
 */
const char* stubids9_ = "rhsfunc(i int, i int, i int[xx], i double[xx], i double[x], i int, i double[xx], i double[xx], io double[x], i int)";

void mexStub9(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int         in0_;    /* nte        */
    int         in1_;    /* np         */
    int*        in2_ =0; /* te2p       */
    double*     in3_ =0; /* p          */
    double*     in4_ =0; /* reg        */
    int         in5_;    /* nsource    */
    double*     in6_ =0; /* rs         */
    double*     in7_ =0; /* js         */
    double*     in8_ =0; /* rhs        */
    int         in9_;    /* iprec      */
    int         dim10_;   /* 4          */
    int         dim11_;   /* nte        */
    int         dim12_;   /* 3          */
    int         dim13_;   /* np         */
    int         dim14_;   /* nte        */
    int         dim15_;   /* 3          */
    int         dim16_;   /* nsource    */
    int         dim17_;   /* 3          */
    int         dim18_;   /* nsource    */
    int         dim19_;   /* np         */

    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (int) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (int) mxWrapGetScalar(prhs[16], &mw_err_txt_);
    dim17_ = (int) mxWrapGetScalar(prhs[17], &mw_err_txt_);
    dim18_ = (int) mxWrapGetScalar(prhs[18], &mw_err_txt_);
    dim19_ = (int) mxWrapGetScalar(prhs[19], &mw_err_txt_);

    if (mxGetM(prhs[2]) != dim10_ ||
        mxGetN(prhs[2]) != dim11_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3]) != dim12_ ||
        mxGetN(prhs[3]) != dim13_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim14_) {
        mw_err_txt_ = "Bad argument size: reg";        goto mw_err_label;
    }

    if (mxGetM(prhs[6]) != dim15_ ||
        mxGetN(prhs[6]) != dim16_) {
        mw_err_txt_ = "Bad argument size: rs";
        goto mw_err_label;
    }

    if (mxGetM(prhs[7]) != dim17_ ||
        mxGetN(prhs[7]) != dim18_) {
        mw_err_txt_ = "Bad argument size: js";
        goto mw_err_label;
    }

    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != dim19_) {
        mw_err_txt_ = "Bad argument size: rhs";        goto mw_err_label;
    }

    in0_ = (int) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in1_ = (int) mxWrapGetScalar(prhs[1], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxGetPr(prhs[4]);
    } else
        in4_ = NULL;
    in5_ = (int) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxGetPr(prhs[6]);
    } else
        in6_ = NULL;
    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != 0) {
        in7_ = mxGetPr(prhs[7]);
    } else
        in7_ = NULL;
    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != 0) {
        in8_ = mxWrapGetArray_double(prhs[8], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in8_ = NULL;
    in9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mexprofrecord_)
        mexprofrecord_[9]++;
    rhsfunc(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, in8_, in9_);
    plhs[0] = mxCreateDoubleMatrix(dim19_, 1, mxREAL);
    mxWrapCopy_double(plhs[0], in8_, dim19_);

mw_err_label:
    if (in2_)  mxFree(in2_);
    if (in8_)  mxFree(in8_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 121 ----
 * rhsfunc2nd(int nte, int np, int[10, nte] te2p, double[3, np] p, double[nte] reg, int nsource, double[3, nsource] rs, double[3, nsource] js, inout double[np] rhs, int iprec);
 */
const char* stubids10_ = "rhsfunc2nd(i int, i int, i int[xx], i double[xx], i double[x], i int, i double[xx], i double[xx], io double[x], i int)";

void mexStub10(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int         in0_;    /* nte        */
    int         in1_;    /* np         */
    int*        in2_ =0; /* te2p       */
    double*     in3_ =0; /* p          */
    double*     in4_ =0; /* reg        */
    int         in5_;    /* nsource    */
    double*     in6_ =0; /* rs         */
    double*     in7_ =0; /* js         */
    double*     in8_ =0; /* rhs        */
    int         in9_;    /* iprec      */
    int         dim10_;   /* 10         */
    int         dim11_;   /* nte        */
    int         dim12_;   /* 3          */
    int         dim13_;   /* np         */
    int         dim14_;   /* nte        */
    int         dim15_;   /* 3          */
    int         dim16_;   /* nsource    */
    int         dim17_;   /* 3          */
    int         dim18_;   /* nsource    */
    int         dim19_;   /* np         */

    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (int) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (int) mxWrapGetScalar(prhs[16], &mw_err_txt_);
    dim17_ = (int) mxWrapGetScalar(prhs[17], &mw_err_txt_);
    dim18_ = (int) mxWrapGetScalar(prhs[18], &mw_err_txt_);
    dim19_ = (int) mxWrapGetScalar(prhs[19], &mw_err_txt_);

    if (mxGetM(prhs[2]) != dim10_ ||
        mxGetN(prhs[2]) != dim11_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3]) != dim12_ ||
        mxGetN(prhs[3]) != dim13_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim14_) {
        mw_err_txt_ = "Bad argument size: reg";        goto mw_err_label;
    }

    if (mxGetM(prhs[6]) != dim15_ ||
        mxGetN(prhs[6]) != dim16_) {
        mw_err_txt_ = "Bad argument size: rs";
        goto mw_err_label;
    }

    if (mxGetM(prhs[7]) != dim17_ ||
        mxGetN(prhs[7]) != dim18_) {
        mw_err_txt_ = "Bad argument size: js";
        goto mw_err_label;
    }

    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != dim19_) {
        mw_err_txt_ = "Bad argument size: rhs";        goto mw_err_label;
    }

    in0_ = (int) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in1_ = (int) mxWrapGetScalar(prhs[1], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxGetPr(prhs[4]);
    } else
        in4_ = NULL;
    in5_ = (int) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxGetPr(prhs[6]);
    } else
        in6_ = NULL;
    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != 0) {
        in7_ = mxGetPr(prhs[7]);
    } else
        in7_ = NULL;
    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != 0) {
        in8_ = mxWrapGetArray_double(prhs[8], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in8_ = NULL;
    in9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mexprofrecord_)
        mexprofrecord_[10]++;
    rhsfunc2nd(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, in8_, in9_);
    plhs[0] = mxCreateDoubleMatrix(dim19_, 1, mxREAL);
    mxWrapCopy_double(plhs[0], in8_, dim19_);

mw_err_label:
    if (in2_)  mxFree(in2_);
    if (in8_)  mxFree(in8_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 123 ----
 * rhsfunc3rd(int nte, int np, int[20, nte] te2p, double[3, np] p, double[nte] reg, int nsource, double[3, nsource] rs, double[3, nsource] js, inout double[np] rhs, int iprec);
 */
const char* stubids11_ = "rhsfunc3rd(i int, i int, i int[xx], i double[xx], i double[x], i int, i double[xx], i double[xx], io double[x], i int)";

void mexStub11(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int         in0_;    /* nte        */
    int         in1_;    /* np         */
    int*        in2_ =0; /* te2p       */
    double*     in3_ =0; /* p          */
    double*     in4_ =0; /* reg        */
    int         in5_;    /* nsource    */
    double*     in6_ =0; /* rs         */
    double*     in7_ =0; /* js         */
    double*     in8_ =0; /* rhs        */
    int         in9_;    /* iprec      */
    int         dim10_;   /* 20         */
    int         dim11_;   /* nte        */
    int         dim12_;   /* 3          */
    int         dim13_;   /* np         */
    int         dim14_;   /* nte        */
    int         dim15_;   /* 3          */
    int         dim16_;   /* nsource    */
    int         dim17_;   /* 3          */
    int         dim18_;   /* nsource    */
    int         dim19_;   /* np         */

    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (int) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (int) mxWrapGetScalar(prhs[16], &mw_err_txt_);
    dim17_ = (int) mxWrapGetScalar(prhs[17], &mw_err_txt_);
    dim18_ = (int) mxWrapGetScalar(prhs[18], &mw_err_txt_);
    dim19_ = (int) mxWrapGetScalar(prhs[19], &mw_err_txt_);

    if (mxGetM(prhs[2]) != dim10_ ||
        mxGetN(prhs[2]) != dim11_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3]) != dim12_ ||
        mxGetN(prhs[3]) != dim13_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim14_) {
        mw_err_txt_ = "Bad argument size: reg";        goto mw_err_label;
    }

    if (mxGetM(prhs[6]) != dim15_ ||
        mxGetN(prhs[6]) != dim16_) {
        mw_err_txt_ = "Bad argument size: rs";
        goto mw_err_label;
    }

    if (mxGetM(prhs[7]) != dim17_ ||
        mxGetN(prhs[7]) != dim18_) {
        mw_err_txt_ = "Bad argument size: js";
        goto mw_err_label;
    }

    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != dim19_) {
        mw_err_txt_ = "Bad argument size: rhs";        goto mw_err_label;
    }

    in0_ = (int) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in1_ = (int) mxWrapGetScalar(prhs[1], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxGetPr(prhs[4]);
    } else
        in4_ = NULL;
    in5_ = (int) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxGetPr(prhs[6]);
    } else
        in6_ = NULL;
    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != 0) {
        in7_ = mxGetPr(prhs[7]);
    } else
        in7_ = NULL;
    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != 0) {
        in8_ = mxWrapGetArray_double(prhs[8], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in8_ = NULL;
    in9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mexprofrecord_)
        mexprofrecord_[11]++;
    rhsfunc3rd(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, in8_, in9_);
    plhs[0] = mxCreateDoubleMatrix(dim19_, 1, mxREAL);
    mxWrapCopy_double(plhs[0], in8_, dim19_);

mw_err_label:
    if (in2_)  mxFree(in2_);
    if (in8_)  mxFree(in8_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 130 ----
 * Eprim(int nsource, int ntarget, double[3, nsource] rs, double[3, nsource] js, double[3, ntarget] robs, inout double[3, ntarget] Eout, int iprecEp);
 */
const char* stubids12_ = "Eprim(i int, i int, i double[xx], i double[xx], i double[xx], io double[xx], i int)";

void mexStub12(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int         in0_;    /* nsource    */
    int         in1_;    /* ntarget    */
    double*     in2_ =0; /* rs         */
    double*     in3_ =0; /* js         */
    double*     in4_ =0; /* robs       */
    double*     in5_ =0; /* Eout       */
    int         in6_;    /* iprecEp    */
    int         dim7_;   /* 3          */
    int         dim8_;   /* nsource    */
    int         dim9_;   /* 3          */
    int         dim10_;   /* nsource    */
    int         dim11_;   /* 3          */
    int         dim12_;   /* ntarget    */
    int         dim13_;   /* 3          */
    int         dim14_;   /* ntarget    */

    dim7_ = (int) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (int) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);

    if (mxGetM(prhs[2]) != dim7_ ||
        mxGetN(prhs[2]) != dim8_) {
        mw_err_txt_ = "Bad argument size: rs";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3]) != dim9_ ||
        mxGetN(prhs[3]) != dim10_) {
        mw_err_txt_ = "Bad argument size: js";
        goto mw_err_label;
    }

    if (mxGetM(prhs[4]) != dim11_ ||
        mxGetN(prhs[4]) != dim12_) {
        mw_err_txt_ = "Bad argument size: robs";
        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim13_ ||
        mxGetN(prhs[5]) != dim14_) {
        mw_err_txt_ = "Bad argument size: Eout";
        goto mw_err_label;
    }

    in0_ = (int) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in1_ = (int) mxWrapGetScalar(prhs[1], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxGetPr(prhs[4]);
    } else
        in4_ = NULL;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_double(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;
    in6_ = (int) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mexprofrecord_)
        mexprofrecord_[12]++;
    Eprim(in0_, in1_, in2_, in3_, in4_, in5_, in6_);
    plhs[0] = mxCreateDoubleMatrix(dim13_, dim14_, mxREAL);
    mxWrapCopy_double(plhs[0], in5_, dim13_*dim14_);

mw_err_label:
    if (in5_)  mxFree(in5_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 141 ----
 * totalEfield(double[3, nobs] robs, int nobs, int[4, nte] te2te, int[4, nte] te2p, int nte, double[3, np] p, double[3, nsource] rs, double[3, nsource] js, int nsource, double[np] xval, inout double[3, nobs] Eout, int iprecEp);
 */
const char* stubids13_ = "totalEfield(i double[xx], i int, i int[xx], i int[xx], i int, i double[xx], i double[xx], i double[xx], i int, i double[x], io double[xx], i int)";

void mexStub13(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double*     in0_ =0; /* robs       */
    int         in1_;    /* nobs       */
    int*        in2_ =0; /* te2te      */
    int*        in3_ =0; /* te2p       */
    int         in4_;    /* nte        */
    double*     in5_ =0; /* p          */
    double*     in6_ =0; /* rs         */
    double*     in7_ =0; /* js         */
    int         in8_;    /* nsource    */
    double*     in9_ =0; /* xval       */
    double*     in10_ =0; /* Eout       */
    int         in11_;    /* iprecEp    */
    int         dim12_;   /* 3          */
    int         dim13_;   /* nobs       */
    int         dim14_;   /* 4          */
    int         dim15_;   /* nte        */
    int         dim16_;   /* 4          */
    int         dim17_;   /* nte        */
    int         dim18_;   /* 3          */
    int         dim19_;   /* np         */
    int         dim20_;   /* 3          */
    int         dim21_;   /* nsource    */
    int         dim22_;   /* 3          */
    int         dim23_;   /* nsource    */
    int         dim24_;   /* np         */
    int         dim25_;   /* 3          */
    int         dim26_;   /* nobs       */

    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (int) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (int) mxWrapGetScalar(prhs[16], &mw_err_txt_);
    dim17_ = (int) mxWrapGetScalar(prhs[17], &mw_err_txt_);
    dim18_ = (int) mxWrapGetScalar(prhs[18], &mw_err_txt_);
    dim19_ = (int) mxWrapGetScalar(prhs[19], &mw_err_txt_);
    dim20_ = (int) mxWrapGetScalar(prhs[20], &mw_err_txt_);
    dim21_ = (int) mxWrapGetScalar(prhs[21], &mw_err_txt_);
    dim22_ = (int) mxWrapGetScalar(prhs[22], &mw_err_txt_);
    dim23_ = (int) mxWrapGetScalar(prhs[23], &mw_err_txt_);
    dim24_ = (int) mxWrapGetScalar(prhs[24], &mw_err_txt_);
    dim25_ = (int) mxWrapGetScalar(prhs[25], &mw_err_txt_);
    dim26_ = (int) mxWrapGetScalar(prhs[26], &mw_err_txt_);

    if (mxGetM(prhs[0]) != dim12_ ||
        mxGetN(prhs[0]) != dim13_) {
        mw_err_txt_ = "Bad argument size: robs";
        goto mw_err_label;
    }

    if (mxGetM(prhs[2]) != dim14_ ||
        mxGetN(prhs[2]) != dim15_) {
        mw_err_txt_ = "Bad argument size: te2te";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3]) != dim16_ ||
        mxGetN(prhs[3]) != dim17_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim18_ ||
        mxGetN(prhs[5]) != dim19_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[6]) != dim20_ ||
        mxGetN(prhs[6]) != dim21_) {
        mw_err_txt_ = "Bad argument size: rs";
        goto mw_err_label;
    }

    if (mxGetM(prhs[7]) != dim22_ ||
        mxGetN(prhs[7]) != dim23_) {
        mw_err_txt_ = "Bad argument size: js";
        goto mw_err_label;
    }

    if (mxGetM(prhs[9])*mxGetN(prhs[9]) != dim24_) {
        mw_err_txt_ = "Bad argument size: xval";        goto mw_err_label;
    }

    if (mxGetM(prhs[10]) != dim25_ ||
        mxGetN(prhs[10]) != dim26_) {
        mw_err_txt_ = "Bad argument size: Eout";
        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxGetPr(prhs[0]);
    } else
        in0_ = NULL;
    in1_ = (int) mxWrapGetScalar(prhs[1], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxWrapGetArray_int(prhs[3], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in3_ = NULL;
    in4_ = (int) mxWrapGetScalar(prhs[4], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxGetPr(prhs[5]);
    } else
        in5_ = NULL;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxGetPr(prhs[6]);
    } else
        in6_ = NULL;
    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != 0) {
        in7_ = mxGetPr(prhs[7]);
    } else
        in7_ = NULL;
    in8_ = (int) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[9])*mxGetN(prhs[9]) != 0) {
        in9_ = mxGetPr(prhs[9]);
    } else
        in9_ = NULL;
    if (mxGetM(prhs[10])*mxGetN(prhs[10]) != 0) {
        in10_ = mxWrapGetArray_double(prhs[10], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in10_ = NULL;
    in11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mexprofrecord_)
        mexprofrecord_[13]++;
    totalEfield(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, in8_, in9_, in10_, in11_);
    plhs[0] = mxCreateDoubleMatrix(dim25_, dim26_, mxREAL);
    mxWrapCopy_double(plhs[0], in10_, dim25_*dim26_);

mw_err_label:
    if (in2_)  mxFree(in2_);
    if (in3_)  mxFree(in3_);
    if (in10_)  mxFree(in10_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 144 ----
 * totalEfield2nd(double[3, nobs] robs, int nobs, int[4, nte] te2te, int[10, nte] te2p, int nte, double[3, np] p, double[3, nsource] rs, double[3, nsource] js, int nsource, double[np] xval, inout double[3, nobs] Eout, int iprecEp);
 */
const char* stubids14_ = "totalEfield2nd(i double[xx], i int, i int[xx], i int[xx], i int, i double[xx], i double[xx], i double[xx], i int, i double[x], io double[xx], i int)";

void mexStub14(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double*     in0_ =0; /* robs       */
    int         in1_;    /* nobs       */
    int*        in2_ =0; /* te2te      */
    int*        in3_ =0; /* te2p       */
    int         in4_;    /* nte        */
    double*     in5_ =0; /* p          */
    double*     in6_ =0; /* rs         */
    double*     in7_ =0; /* js         */
    int         in8_;    /* nsource    */
    double*     in9_ =0; /* xval       */
    double*     in10_ =0; /* Eout       */
    int         in11_;    /* iprecEp    */
    int         dim12_;   /* 3          */
    int         dim13_;   /* nobs       */
    int         dim14_;   /* 4          */
    int         dim15_;   /* nte        */
    int         dim16_;   /* 10         */
    int         dim17_;   /* nte        */
    int         dim18_;   /* 3          */
    int         dim19_;   /* np         */
    int         dim20_;   /* 3          */
    int         dim21_;   /* nsource    */
    int         dim22_;   /* 3          */
    int         dim23_;   /* nsource    */
    int         dim24_;   /* np         */
    int         dim25_;   /* 3          */
    int         dim26_;   /* nobs       */

    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (int) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (int) mxWrapGetScalar(prhs[16], &mw_err_txt_);
    dim17_ = (int) mxWrapGetScalar(prhs[17], &mw_err_txt_);
    dim18_ = (int) mxWrapGetScalar(prhs[18], &mw_err_txt_);
    dim19_ = (int) mxWrapGetScalar(prhs[19], &mw_err_txt_);
    dim20_ = (int) mxWrapGetScalar(prhs[20], &mw_err_txt_);
    dim21_ = (int) mxWrapGetScalar(prhs[21], &mw_err_txt_);
    dim22_ = (int) mxWrapGetScalar(prhs[22], &mw_err_txt_);
    dim23_ = (int) mxWrapGetScalar(prhs[23], &mw_err_txt_);
    dim24_ = (int) mxWrapGetScalar(prhs[24], &mw_err_txt_);
    dim25_ = (int) mxWrapGetScalar(prhs[25], &mw_err_txt_);
    dim26_ = (int) mxWrapGetScalar(prhs[26], &mw_err_txt_);

    if (mxGetM(prhs[0]) != dim12_ ||
        mxGetN(prhs[0]) != dim13_) {
        mw_err_txt_ = "Bad argument size: robs";
        goto mw_err_label;
    }

    if (mxGetM(prhs[2]) != dim14_ ||
        mxGetN(prhs[2]) != dim15_) {
        mw_err_txt_ = "Bad argument size: te2te";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3]) != dim16_ ||
        mxGetN(prhs[3]) != dim17_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim18_ ||
        mxGetN(prhs[5]) != dim19_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[6]) != dim20_ ||
        mxGetN(prhs[6]) != dim21_) {
        mw_err_txt_ = "Bad argument size: rs";
        goto mw_err_label;
    }

    if (mxGetM(prhs[7]) != dim22_ ||
        mxGetN(prhs[7]) != dim23_) {
        mw_err_txt_ = "Bad argument size: js";
        goto mw_err_label;
    }

    if (mxGetM(prhs[9])*mxGetN(prhs[9]) != dim24_) {
        mw_err_txt_ = "Bad argument size: xval";        goto mw_err_label;
    }

    if (mxGetM(prhs[10]) != dim25_ ||
        mxGetN(prhs[10]) != dim26_) {
        mw_err_txt_ = "Bad argument size: Eout";
        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxGetPr(prhs[0]);
    } else
        in0_ = NULL;
    in1_ = (int) mxWrapGetScalar(prhs[1], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxWrapGetArray_int(prhs[3], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in3_ = NULL;
    in4_ = (int) mxWrapGetScalar(prhs[4], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxGetPr(prhs[5]);
    } else
        in5_ = NULL;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxGetPr(prhs[6]);
    } else
        in6_ = NULL;
    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != 0) {
        in7_ = mxGetPr(prhs[7]);
    } else
        in7_ = NULL;
    in8_ = (int) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[9])*mxGetN(prhs[9]) != 0) {
        in9_ = mxGetPr(prhs[9]);
    } else
        in9_ = NULL;
    if (mxGetM(prhs[10])*mxGetN(prhs[10]) != 0) {
        in10_ = mxWrapGetArray_double(prhs[10], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in10_ = NULL;
    in11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mexprofrecord_)
        mexprofrecord_[14]++;
    totalEfield2nd(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, in8_, in9_, in10_, in11_);
    plhs[0] = mxCreateDoubleMatrix(dim25_, dim26_, mxREAL);
    mxWrapCopy_double(plhs[0], in10_, dim25_*dim26_);

mw_err_label:
    if (in2_)  mxFree(in2_);
    if (in3_)  mxFree(in3_);
    if (in10_)  mxFree(in10_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 147 ----
 * totalEfield3rd(double[3, nobs] robs, int nobs, int[4, nte] te2te, int[20, nte] te2p, int nte, double[3, np] p, double[3, nsource] rs, double[3, nsource] js, int nsource, double[np] xval, inout double[3, nobs] Eout, int iprecEp);
 */
const char* stubids15_ = "totalEfield3rd(i double[xx], i int, i int[xx], i int[xx], i int, i double[xx], i double[xx], i double[xx], i int, i double[x], io double[xx], i int)";

void mexStub15(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double*     in0_ =0; /* robs       */
    int         in1_;    /* nobs       */
    int*        in2_ =0; /* te2te      */
    int*        in3_ =0; /* te2p       */
    int         in4_;    /* nte        */
    double*     in5_ =0; /* p          */
    double*     in6_ =0; /* rs         */
    double*     in7_ =0; /* js         */
    int         in8_;    /* nsource    */
    double*     in9_ =0; /* xval       */
    double*     in10_ =0; /* Eout       */
    int         in11_;    /* iprecEp    */
    int         dim12_;   /* 3          */
    int         dim13_;   /* nobs       */
    int         dim14_;   /* 4          */
    int         dim15_;   /* nte        */
    int         dim16_;   /* 20         */
    int         dim17_;   /* nte        */
    int         dim18_;   /* 3          */
    int         dim19_;   /* np         */
    int         dim20_;   /* 3          */
    int         dim21_;   /* nsource    */
    int         dim22_;   /* 3          */
    int         dim23_;   /* nsource    */
    int         dim24_;   /* np         */
    int         dim25_;   /* 3          */
    int         dim26_;   /* nobs       */

    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (int) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (int) mxWrapGetScalar(prhs[16], &mw_err_txt_);
    dim17_ = (int) mxWrapGetScalar(prhs[17], &mw_err_txt_);
    dim18_ = (int) mxWrapGetScalar(prhs[18], &mw_err_txt_);
    dim19_ = (int) mxWrapGetScalar(prhs[19], &mw_err_txt_);
    dim20_ = (int) mxWrapGetScalar(prhs[20], &mw_err_txt_);
    dim21_ = (int) mxWrapGetScalar(prhs[21], &mw_err_txt_);
    dim22_ = (int) mxWrapGetScalar(prhs[22], &mw_err_txt_);
    dim23_ = (int) mxWrapGetScalar(prhs[23], &mw_err_txt_);
    dim24_ = (int) mxWrapGetScalar(prhs[24], &mw_err_txt_);
    dim25_ = (int) mxWrapGetScalar(prhs[25], &mw_err_txt_);
    dim26_ = (int) mxWrapGetScalar(prhs[26], &mw_err_txt_);

    if (mxGetM(prhs[0]) != dim12_ ||
        mxGetN(prhs[0]) != dim13_) {
        mw_err_txt_ = "Bad argument size: robs";
        goto mw_err_label;
    }

    if (mxGetM(prhs[2]) != dim14_ ||
        mxGetN(prhs[2]) != dim15_) {
        mw_err_txt_ = "Bad argument size: te2te";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3]) != dim16_ ||
        mxGetN(prhs[3]) != dim17_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim18_ ||
        mxGetN(prhs[5]) != dim19_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[6]) != dim20_ ||
        mxGetN(prhs[6]) != dim21_) {
        mw_err_txt_ = "Bad argument size: rs";
        goto mw_err_label;
    }

    if (mxGetM(prhs[7]) != dim22_ ||
        mxGetN(prhs[7]) != dim23_) {
        mw_err_txt_ = "Bad argument size: js";
        goto mw_err_label;
    }

    if (mxGetM(prhs[9])*mxGetN(prhs[9]) != dim24_) {
        mw_err_txt_ = "Bad argument size: xval";        goto mw_err_label;
    }

    if (mxGetM(prhs[10]) != dim25_ ||
        mxGetN(prhs[10]) != dim26_) {
        mw_err_txt_ = "Bad argument size: Eout";
        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxGetPr(prhs[0]);
    } else
        in0_ = NULL;
    in1_ = (int) mxWrapGetScalar(prhs[1], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxWrapGetArray_int(prhs[3], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in3_ = NULL;
    in4_ = (int) mxWrapGetScalar(prhs[4], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxGetPr(prhs[5]);
    } else
        in5_ = NULL;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxGetPr(prhs[6]);
    } else
        in6_ = NULL;
    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != 0) {
        in7_ = mxGetPr(prhs[7]);
    } else
        in7_ = NULL;
    in8_ = (int) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[9])*mxGetN(prhs[9]) != 0) {
        in9_ = mxGetPr(prhs[9]);
    } else
        in9_ = NULL;
    if (mxGetM(prhs[10])*mxGetN(prhs[10]) != 0) {
        in10_ = mxWrapGetArray_double(prhs[10], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in10_ = NULL;
    in11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mexprofrecord_)
        mexprofrecord_[15]++;
    totalEfield3rd(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, in8_, in9_, in10_, in11_);
    plhs[0] = mxCreateDoubleMatrix(dim25_, dim26_, mxREAL);
    mxWrapCopy_double(plhs[0], in10_, dim25_*dim26_);

mw_err_label:
    if (in2_)  mxFree(in2_);
    if (in3_)  mxFree(in3_);
    if (in10_)  mxFree(in10_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 157 ----
 * pointLocation_f(double[3, nobs] robs, int nobs, int[te_stride, nte] te2p, int nte, double[3, np] p, int te_stride, int[4, nte] te2te, inout int[nobs] teid, inout double[4, nobs] bari);
 */
const char* stubids16_ = "pointLocation_f(i double[xx], i int, i int[xx], i int, i double[xx], i int, i int[xx], io int[x], io double[xx])";

void mexStub16(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double*     in0_ =0; /* robs       */
    int         in1_;    /* nobs       */
    int*        in2_ =0; /* te2p       */
    int         in3_;    /* nte        */
    double*     in4_ =0; /* p          */
    int         in5_;    /* te_stride  */
    int*        in6_ =0; /* te2te      */
    int*        in7_ =0; /* teid       */
    double*     in8_ =0; /* bari       */
    int         dim9_;   /* 3          */
    int         dim10_;   /* nobs       */
    int         dim11_;   /* te_stride  */
    int         dim12_;   /* nte        */
    int         dim13_;   /* 3          */
    int         dim14_;   /* np         */
    int         dim15_;   /* 4          */
    int         dim16_;   /* nte        */
    int         dim17_;   /* nobs       */
    int         dim18_;   /* 4          */
    int         dim19_;   /* nobs       */

    dim9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (int) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (int) mxWrapGetScalar(prhs[16], &mw_err_txt_);
    dim17_ = (int) mxWrapGetScalar(prhs[17], &mw_err_txt_);
    dim18_ = (int) mxWrapGetScalar(prhs[18], &mw_err_txt_);
    dim19_ = (int) mxWrapGetScalar(prhs[19], &mw_err_txt_);

    if (mxGetM(prhs[0]) != dim9_ ||
        mxGetN(prhs[0]) != dim10_) {
        mw_err_txt_ = "Bad argument size: robs";
        goto mw_err_label;
    }

    if (mxGetM(prhs[2]) != dim11_ ||
        mxGetN(prhs[2]) != dim12_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[4]) != dim13_ ||
        mxGetN(prhs[4]) != dim14_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[6]) != dim15_ ||
        mxGetN(prhs[6]) != dim16_) {
        mw_err_txt_ = "Bad argument size: te2te";
        goto mw_err_label;
    }

    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != dim17_) {
        mw_err_txt_ = "Bad argument size: teid";        goto mw_err_label;
    }

    if (mxGetM(prhs[8]) != dim18_ ||
        mxGetN(prhs[8]) != dim19_) {
        mw_err_txt_ = "Bad argument size: bari";
        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxGetPr(prhs[0]);
    } else
        in0_ = NULL;
    in1_ = (int) mxWrapGetScalar(prhs[1], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;
    in3_ = (int) mxWrapGetScalar(prhs[3], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxGetPr(prhs[4]);
    } else
        in4_ = NULL;
    in5_ = (int) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxWrapGetArray_int(prhs[6], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in6_ = NULL;
    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != 0) {
        in7_ = mxWrapGetArray_int(prhs[7], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in7_ = NULL;
    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != 0) {
        in8_ = mxWrapGetArray_double(prhs[8], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in8_ = NULL;
    if (mexprofrecord_)
        mexprofrecord_[16]++;
    pointLocation_f(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, in8_);
    plhs[0] = mxCreateDoubleMatrix(dim17_, 1, mxREAL);
    mxWrapCopy_int(plhs[0], in7_, dim17_);
    plhs[1] = mxCreateDoubleMatrix(dim18_, dim19_, mxREAL);
    mxWrapCopy_double(plhs[1], in8_, dim18_*dim19_);

mw_err_label:
    if (in2_)  mxFree(in2_);
    if (in6_)  mxFree(in6_);
    if (in7_)  mxFree(in7_);
    if (in8_)  mxFree(in8_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 165 ----
 * generatetetrapaths(int nte, int[4, nte] te2p, inout int[4, nte] te2te);
 */
const char* stubids17_ = "generatetetrapaths(i int, i int[xx], io int[xx])";

void mexStub17(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int         in0_;    /* nte        */
    int*        in1_ =0; /* te2p       */
    int*        in2_ =0; /* te2te      */
    int         dim3_;   /* 4          */
    int         dim4_;   /* nte        */
    int         dim5_;   /* 4          */
    int         dim6_;   /* nte        */

    dim3_ = (int) mxWrapGetScalar(prhs[3], &mw_err_txt_);
    dim4_ = (int) mxWrapGetScalar(prhs[4], &mw_err_txt_);
    dim5_ = (int) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    dim6_ = (int) mxWrapGetScalar(prhs[6], &mw_err_txt_);

    if (mxGetM(prhs[1]) != dim3_ ||
        mxGetN(prhs[1]) != dim4_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[2]) != dim5_ ||
        mxGetN(prhs[2]) != dim6_) {
        mw_err_txt_ = "Bad argument size: te2te";
        goto mw_err_label;
    }

    in0_ = (int) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;
    if (mexprofrecord_)
        mexprofrecord_[17]++;
    generatetetrapaths(in0_, in1_, in2_);
    plhs[0] = mxCreateDoubleMatrix(dim5_, dim6_, mxREAL);
    mxWrapCopy_int(plhs[0], in2_, dim5_*dim6_);

mw_err_label:
    if (in1_)  mxFree(in1_);
    if (in2_)  mxFree(in2_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ----
 */
void mexFunction(int nlhs, mxArray* plhs[],
                 int nrhs, const mxArray* prhs[])
{
    char id[512];
    if (nrhs == 0) {
        mexPrintf("Mex function installed\n");
        return;
    }

    if (mxGetString(prhs[0], id, sizeof(id)) != 0)
        mexErrMsgTxt("Identifier should be a string");
    else if (strcmp(id, stubids1_) == 0)
        mexStub1(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids2_) == 0)
        mexStub2(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids3_) == 0)
        mexStub3(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids4_) == 0)
        mexStub4(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids5_) == 0)
        mexStub5(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids6_) == 0)
        mexStub6(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids7_) == 0)
        mexStub7(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids8_) == 0)
        mexStub8(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids9_) == 0)
        mexStub9(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids10_) == 0)
        mexStub10(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids11_) == 0)
        mexStub11(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids12_) == 0)
        mexStub12(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids13_) == 0)
        mexStub13(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids14_) == 0)
        mexStub14(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids15_) == 0)
        mexStub15(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids16_) == 0)
        mexStub16(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids17_) == 0)
        mexStub17(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, "*profile on*") == 0) {
        if (!mexprofrecord_) {
            mexprofrecord_ = (int*) malloc(18 * sizeof(int));
            mexLock();
        }
        memset(mexprofrecord_, 0, 18 * sizeof(int));
    } else if (strcmp(id, "*profile off*") == 0) {
        if (mexprofrecord_) {
            free(mexprofrecord_);
            mexUnlock();
        }
        mexprofrecord_ = NULL;
    } else if (strcmp(id, "*profile report*") == 0) {
        if (!mexprofrecord_)
            mexPrintf("Profiler inactive\n");
        mexPrintf("%d calls to demo.mw:75\n", mexprofrecord_[1]);
        mexPrintf("%d calls to demo.mw:78\n", mexprofrecord_[2]);
        mexPrintf("%d calls to demo.mw:80\n", mexprofrecord_[3]);
        mexPrintf("%d calls to demo.mw:81\n", mexprofrecord_[4]);
        mexPrintf("%d calls to demo.mw:84\n", mexprofrecord_[5]);
        mexPrintf("%d calls to demo.mw:95\n", mexprofrecord_[6]);
        mexPrintf("%d calls to demo.mw:100\n", mexprofrecord_[7]);
        mexPrintf("%d calls to demo.mw:105\n", mexprofrecord_[8]);
        mexPrintf("%d calls to demo.mw:119\n", mexprofrecord_[9]);
        mexPrintf("%d calls to demo.mw:121\n", mexprofrecord_[10]);
        mexPrintf("%d calls to demo.mw:123\n", mexprofrecord_[11]);
        mexPrintf("%d calls to demo.mw:130\n", mexprofrecord_[12]);
        mexPrintf("%d calls to demo.mw:141\n", mexprofrecord_[13]);
        mexPrintf("%d calls to demo.mw:144\n", mexprofrecord_[14]);
        mexPrintf("%d calls to demo.mw:147\n", mexprofrecord_[15]);
        mexPrintf("%d calls to demo.mw:157\n", mexprofrecord_[16]);
        mexPrintf("%d calls to demo.mw:165\n", mexprofrecord_[17]);
    } else if (strcmp(id, "*profile log*") == 0) {
        FILE* logfp;
        if (nrhs != 2 || mxGetString(prhs[1], id, sizeof(id)) != 0)
            mexErrMsgTxt("Must have two string arguments");
        logfp = fopen(id, "w+");
        if (!logfp)
            mexErrMsgTxt("Cannot open log for output");
        if (!mexprofrecord_)
            fprintf(logfp, "Profiler inactive\n");
        fprintf(logfp, "%d calls to demo.mw:75\n", mexprofrecord_[1]);
        fprintf(logfp, "%d calls to demo.mw:78\n", mexprofrecord_[2]);
        fprintf(logfp, "%d calls to demo.mw:80\n", mexprofrecord_[3]);
        fprintf(logfp, "%d calls to demo.mw:81\n", mexprofrecord_[4]);
        fprintf(logfp, "%d calls to demo.mw:84\n", mexprofrecord_[5]);
        fprintf(logfp, "%d calls to demo.mw:95\n", mexprofrecord_[6]);
        fprintf(logfp, "%d calls to demo.mw:100\n", mexprofrecord_[7]);
        fprintf(logfp, "%d calls to demo.mw:105\n", mexprofrecord_[8]);
        fprintf(logfp, "%d calls to demo.mw:119\n", mexprofrecord_[9]);
        fprintf(logfp, "%d calls to demo.mw:121\n", mexprofrecord_[10]);
        fprintf(logfp, "%d calls to demo.mw:123\n", mexprofrecord_[11]);
        fprintf(logfp, "%d calls to demo.mw:130\n", mexprofrecord_[12]);
        fprintf(logfp, "%d calls to demo.mw:141\n", mexprofrecord_[13]);
        fprintf(logfp, "%d calls to demo.mw:144\n", mexprofrecord_[14]);
        fprintf(logfp, "%d calls to demo.mw:147\n", mexprofrecord_[15]);
        fprintf(logfp, "%d calls to demo.mw:157\n", mexprofrecord_[16]);
        fprintf(logfp, "%d calls to demo.mw:165\n", mexprofrecord_[17]);
        fclose(logfp);
    } else
        mexErrMsgTxt("Unknown identifier");
}

