#include <uchar.h>
int countfaces(const int nte,const  int* te2p,const double* condu,int* np);
void makeBEMmesh(const int nte,const  int* te2p,const double* p,const double* condu,int* t2p,double* pbem,double* epseff);
/* --------------------------------------------------- */
/* Automatically generated by mwrap                    */
/* --------------------------------------------------- */

/* Code generated by mwrap */
/*
  Copyright statement for mwrap:

  mwrap -- MEX file generation for MATLAB and Octave
  Copyright (c) 2007-2008 David Bindel

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  You may distribute a work that contains part or all of the source code
  generated by mwrap under the terms of your choice.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/

#include <mex.h>
#include <stdio.h>
#include <string.h>


#ifndef ulong
#  define ulong unsigned long
#endif
#ifndef uint
#  define uint  unsigned int
#endif
#ifndef uchar
#  define uchar unsigned char
#endif


/*
 * Records for call profile.
 */
int* mexprofrecord_= NULL;


/*
 * Support routines for copying data into and out of the MEX stubs
 */

void* mxWrapGetP(const mxArray* a, const char* fmt, const char** e)
{
    void* p = 0;
    mxArray* ap;
    if (mxGetClassID(a) == mxDOUBLE_CLASS && 
        mxGetM(a)*mxGetN(a) == 1 && *mxGetPr(a) == 0)
        return p;
    if (mxIsChar(a)) {
        char pbuf[128];
        mxGetString(a, pbuf, sizeof(pbuf));
        sscanf(pbuf, fmt, &p);
    } 
#ifdef R2008OO
    else if (ap = mxGetProperty(a, 0, "mwptr")) {
        return mxWrapGetP(ap, fmt, e);
    }
#endif
    if (p == 0)
        *e = "Invalid pointer";
    return p;
}

mxArray* mxWrapCreateP(void* p, const char* fmt)
{
    if (p == 0) {
        mxArray* z = mxCreateDoubleMatrix(1,1, mxREAL);
        *mxGetPr(z) = 0;
        return z;
    } else {
        char pbuf[128];
        sprintf(pbuf, fmt, p);
        return mxCreateString(pbuf);
    }
}

mxArray* mxWrapStrncpy(const char* s)
{
    if (s) {
        return mxCreateString(s);
    } else {
        mxArray* z = mxCreateDoubleMatrix(1,1, mxREAL);
        *mxGetPr(z) = 0;
        return z;
    }
}

double mxWrapGetScalar(const mxArray* a, const char** e)
{
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS || mxGetM(a)*mxGetN(a) != 1) {
        *e = "Invalid scalar argument";
        return 0;
    }
    return *mxGetPr(a);
}

char* mxWrapGetString(const mxArray* a, const char** e)
{
    char* s;
    int slen;
    if (!a || (!mxIsChar(a) && mxGetM(a)*mxGetN(a) > 0)) {
        *e = "Invalid string argument";
        return NULL;
    }
    slen = mxGetM(a)*mxGetN(a) + 1;
    s = (char*) mxMalloc(slen);
    if (mxGetM(a)*mxGetN(a) == 0)
        *s = 0;
    else
        mxGetString(a, s, slen);
    return s;
}


#define mxWrapGetArrayDef(func, T) \
T* func(const mxArray* a, const char** e)     \
{ \
    T* array; \
    int arraylen; \
    int i; \
    T* p; \
    double* q; \
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS) { \
        *e = "Invalid array argument"; \
        return 0; \
    } \
    arraylen = mxGetM(a)*mxGetN(a); \
    array = (T*) mxMalloc(mxGetM(a)*mxGetN(a) * sizeof(T)); \
    p = array; \
    q = mxGetPr(a); \
    for (i = 0; i < arraylen; ++i) \
        *p++ = (T) (*q++); \
    return array; \
}


#define mxWrapCopyDef(func, T) \
void func(mxArray* a, const T* q, int n) \
{ \
    int i; \
    double* p = mxGetPr(a); \
    for (i = 0; i < n; ++i) \
        *p++ = *q++; \
}


#define mxWrapReturnDef(func, T) \
mxArray* func(const T* q, int m, int n) \
{ \
    int i; \
    double* p; \
    if (!q) { \
        return mxCreateDoubleMatrix(0,0, mxREAL); \
    } else { \
        mxArray* a = mxCreateDoubleMatrix(m,n, mxREAL); \
        p = mxGetPr(a); \
        for (i = 0; i < m*n; ++i) \
            *p++ = *q++; \
        return a; \
    } \
}


#define mxWrapGetScalarZDef(func, T, ZT, setz) \
void func(T* z, const mxArray* a) \
{ \
    double* pr = mxGetPr(a); \
    double* pi = mxGetPi(a); \
    setz(z, (ZT) *pr, (pi ? (ZT) *pi : (ZT) 0)); \
}


#define mxWrapGetArrayZDef(func, T, ZT, setz) \
T* func(const mxArray* a, const char** e) \
{ \
    T* array; \
    int arraylen; \
    int i; \
    T* p; \
    double* qr; \
    double* qi; \
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS) { \
        *e = "Invalid array argument"; \
        return 0; \
    } \
    arraylen = mxGetM(a)*mxGetN(a); \
    array = (T*) mxMalloc(mxGetM(a)*mxGetN(a) * sizeof(T)); \
    p = array; \
    qr = mxGetPr(a); \
    qi = mxGetPi(a); \
    for (i = 0; i < arraylen; ++i) { \
        ZT val_qr = *qr++; \
        ZT val_qi = (qi ? (ZT) *qi++ : (ZT) 0); \
        setz(p, val_qr, val_qi); \
        ++p; \
    } \
    return array; \
}


#define mxWrapCopyZDef(func, T, real, imag) \
void func(mxArray* a, const T* q, int n) \
{ \
    int i; \
    double* pr = mxGetPr(a); \
    double* pi = mxGetPi(a); \
    for (i = 0; i < n; ++i) { \
        *pr++ = real(*q); \
        *pi++ = imag(*q); \
        ++q; \
    } \
}


#define mxWrapReturnZDef(func, T, real, imag) \
mxArray* func(const T* q, int m, int n) \
{ \
    int i; \
    double* pr; \
    double* pi; \
    if (!q) { \
        return mxCreateDoubleMatrix(0,0, mxCOMPLEX); \
    } else { \
        mxArray* a = mxCreateDoubleMatrix(m,n, mxCOMPLEX); \
        pr = mxGetPr(a); \
        pi = mxGetPi(a); \
        for (i = 0; i < m*n; ++i) { \
            *pr++ = real(*q); \
            *pi++ = imag(*q); \
            ++q; \
        } \
        return a; \
    } \
}

/* Array copier definitions */
mxWrapGetArrayDef(mxWrapGetArray_bool, bool)
mxWrapCopyDef    (mxWrapCopy_bool,     bool)
mxWrapReturnDef  (mxWrapReturn_bool,   bool)
mxWrapGetArrayDef(mxWrapGetArray_char, char)
mxWrapCopyDef    (mxWrapCopy_char,     char)
mxWrapReturnDef  (mxWrapReturn_char,   char)
mxWrapGetArrayDef(mxWrapGetArray_double, double)
mxWrapCopyDef    (mxWrapCopy_double,     double)
mxWrapReturnDef  (mxWrapReturn_double,   double)
mxWrapGetArrayDef(mxWrapGetArray_float, float)
mxWrapCopyDef    (mxWrapCopy_float,     float)
mxWrapReturnDef  (mxWrapReturn_float,   float)
mxWrapGetArrayDef(mxWrapGetArray_int, int)
mxWrapCopyDef    (mxWrapCopy_int,     int)
mxWrapReturnDef  (mxWrapReturn_int,   int)
mxWrapGetArrayDef(mxWrapGetArray_long, long)
mxWrapCopyDef    (mxWrapCopy_long,     long)
mxWrapReturnDef  (mxWrapReturn_long,   long)
mxWrapGetArrayDef(mxWrapGetArray_size_t, size_t)
mxWrapCopyDef    (mxWrapCopy_size_t,     size_t)
mxWrapReturnDef  (mxWrapReturn_size_t,   size_t)
mxWrapGetArrayDef(mxWrapGetArray_uchar, uchar)
mxWrapCopyDef    (mxWrapCopy_uchar,     uchar)
mxWrapReturnDef  (mxWrapReturn_uchar,   uchar)
mxWrapGetArrayDef(mxWrapGetArray_uint, uint)
mxWrapCopyDef    (mxWrapCopy_uint,     uint)
mxWrapReturnDef  (mxWrapReturn_uint,   uint)
mxWrapGetArrayDef(mxWrapGetArray_ulong, ulong)
mxWrapCopyDef    (mxWrapCopy_ulong,     ulong)
mxWrapReturnDef  (mxWrapReturn_ulong,   ulong)

#if defined(MWF77_CAPS)
#define MWF77_generategroupct GENERATEGROUPCT
#define MWF77_generategroupmatlab GENERATEGROUPMATLAB
#define MWF77_createbemdatastructmatlab CREATEBEMDATASTRUCTMATLAB
#define MWF77_computerhsmatlab COMPUTERHSMATLAB
#define MWF77_fmmchargematlab FMMCHARGEMATLAB
#define MWF77_bemsolver BEMSOLVER
#define MWF77_evaluateEfield EVALUATEEFIELD
#elif defined(MWF77_UNDERSCORE1)
#define MWF77_generategroupct generategroupct_
#define MWF77_generategroupmatlab generategroupmatlab_
#define MWF77_createbemdatastructmatlab createbemdatastructmatlab_
#define MWF77_computerhsmatlab computerhsmatlab_
#define MWF77_fmmchargematlab fmmchargematlab_
#define MWF77_bemsolver bemsolver_
#define MWF77_evaluateEfield evaluateefield_
#else /* f2c convention */
#define MWF77_generategroupct generategroupct_
#define MWF77_generategroupmatlab generategroupmatlab_
#define MWF77_createbemdatastructmatlab createbemdatastructmatlab_
#define MWF77_computerhsmatlab computerhsmatlab_
#define MWF77_fmmchargematlab fmmchargematlab_
#define MWF77_bemsolver bemsolver_
#define MWF77_evaluateEfield evaluateefield_
#endif

#ifdef __cplusplus
extern "C" { /* Prevent C++ name mangling */
#endif

#ifndef MWF77_RETURN
#define MWF77_RETURN int
#endif

MWF77_RETURN MWF77_generategroupct(int*, int*, double*, int*, double*, int*);
MWF77_RETURN MWF77_generategroupmatlab(int*, int*, double*, int*, double*, int*, int*, int*);
MWF77_RETURN MWF77_createbemdatastructmatlab(int*, int*, double*, int*, double*, double*, int*, int*, int*, double*, double*, int*, int*, int*, double*);
MWF77_RETURN MWF77_computerhsmatlab(int*, int*, double*, int*, double*, double*, double*, int*, int*, double*);
MWF77_RETURN MWF77_fmmchargematlab(double*, double*, int*, double*, int*);
MWF77_RETURN MWF77_bemsolver(int*, int*, double*, int*, double*, double*, double*, int*, double*, int*, int*, double*, int*, double*);
MWF77_RETURN MWF77_evaluateEfield(int*, int*, double*, int*, double*, double*, double*, int*, double*, double*, int*, double*, int*, int*, double*);

#ifdef __cplusplus
} /* end extern C */
#endif

/* ---- demo.mw: 54 ----
 * generategroupct(int[3, nt] t2p, int[1] nt, double[3, np] p, int[1] np, double[1] del, output int[1] ncol);
 */
const char* stubids1_ = "generategroupct(i int[xx], i int[x], i double[xx], i int[x], i double[x], o int[x])";

void mexStub1(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int*        in0_ =0; /* t2p        */
    int*        in1_ =0; /* nt         */
    double*     in2_ =0; /* p          */
    int*        in3_ =0; /* np         */
    double*     in4_ =0; /* del        */
    int*        out0_=0; /* ncol       */
    int         dim5_;   /* 3          */
    int         dim6_;   /* nt         */
    int         dim7_;   /* 1          */
    int         dim8_;   /* 3          */
    int         dim9_;   /* np         */
    int         dim10_;   /* 1          */
    int         dim11_;   /* 1          */
    int         dim12_;   /* 1          */

    dim5_ = (int) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    dim6_ = (int) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    dim7_ = (int) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (int) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);

    if (mxGetM(prhs[0]) != dim5_ ||
        mxGetN(prhs[0]) != dim6_) {
        mw_err_txt_ = "Bad argument size: t2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != dim7_) {
        mw_err_txt_ = "Bad argument size: nt";        goto mw_err_label;
    }

    if (mxGetM(prhs[2]) != dim8_ ||
        mxGetN(prhs[2]) != dim9_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != dim10_) {
        mw_err_txt_ = "Bad argument size: np";        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim11_) {
        mw_err_txt_ = "Bad argument size: del";        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxWrapGetArray_int(prhs[0], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in0_ = NULL;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxWrapGetArray_int(prhs[3], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxGetPr(prhs[4]);
    } else
        in4_ = NULL;
    out0_ = (int*) mxMalloc(dim12_*sizeof(int));
    if (mexprofrecord_)
        mexprofrecord_[1]++;
    MWF77_generategroupct(in0_, in1_, in2_, in3_, in4_, out0_);
    plhs[0] = mxCreateDoubleMatrix(dim12_, 1, mxREAL);
    mxWrapCopy_int(plhs[0], out0_, dim12_);

mw_err_label:
    if (in0_)  mxFree(in0_);
    if (in1_)  mxFree(in1_);
    if (in3_)  mxFree(in3_);
    if (out0_) mxFree(out0_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 56 ----
 * generategroupmatlab(int[3, nt] t2p, int[1] nt, double[3, np] p, int[1] np, double[1] del, output int[ncol] col, output int[ncol] row, int[1] ncol);
 */
const char* stubids2_ = "generategroupmatlab(i int[xx], i int[x], i double[xx], i int[x], i double[x], o int[x], o int[x], i int[x])";

void mexStub2(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int*        in0_ =0; /* t2p        */
    int*        in1_ =0; /* nt         */
    double*     in2_ =0; /* p          */
    int*        in3_ =0; /* np         */
    double*     in4_ =0; /* del        */
    int*        in5_ =0; /* ncol       */
    int*        out0_=0; /* col        */
    int*        out1_=0; /* row        */
    int         dim6_;   /* 3          */
    int         dim7_;   /* nt         */
    int         dim8_;   /* 1          */
    int         dim9_;   /* 3          */
    int         dim10_;   /* np         */
    int         dim11_;   /* 1          */
    int         dim12_;   /* 1          */
    int         dim13_;   /* ncol       */
    int         dim14_;   /* ncol       */
    int         dim15_;   /* 1          */

    dim6_ = (int) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    dim7_ = (int) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (int) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (int) mxWrapGetScalar(prhs[15], &mw_err_txt_);

    if (mxGetM(prhs[0]) != dim6_ ||
        mxGetN(prhs[0]) != dim7_) {
        mw_err_txt_ = "Bad argument size: t2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != dim8_) {
        mw_err_txt_ = "Bad argument size: nt";        goto mw_err_label;
    }

    if (mxGetM(prhs[2]) != dim9_ ||
        mxGetN(prhs[2]) != dim10_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != dim11_) {
        mw_err_txt_ = "Bad argument size: np";        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim12_) {
        mw_err_txt_ = "Bad argument size: del";        goto mw_err_label;
    }

    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != dim15_) {
        mw_err_txt_ = "Bad argument size: ncol";        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxWrapGetArray_int(prhs[0], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in0_ = NULL;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxWrapGetArray_int(prhs[3], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxGetPr(prhs[4]);
    } else
        in4_ = NULL;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_int(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;
    out0_ = (int*) mxMalloc(dim13_*sizeof(int));
    out1_ = (int*) mxMalloc(dim14_*sizeof(int));
    if (mexprofrecord_)
        mexprofrecord_[2]++;
    MWF77_generategroupmatlab(in0_, in1_, in2_, in3_, in4_, out0_, out1_, in5_);
    plhs[0] = mxCreateDoubleMatrix(dim13_, 1, mxREAL);
    mxWrapCopy_int(plhs[0], out0_, dim13_);
    plhs[1] = mxCreateDoubleMatrix(dim14_, 1, mxREAL);
    mxWrapCopy_int(plhs[1], out1_, dim14_);

mw_err_label:
    if (in0_)  mxFree(in0_);
    if (in1_)  mxFree(in1_);
    if (in3_)  mxFree(in3_);
    if (out0_) mxFree(out0_);
    if (out1_) mxFree(out1_);
    if (in5_)  mxFree(in5_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 61 ----
 * createbemdatastructmatlab(int[3, nt] t2p, int[1] nt, double[3, np] p, int[1] np, double[nt] area, double[3, nt] normal, int[ncols] row, int[ncols] col, int[1] ncols, output double[ncols] potout, output double[3, nt3] triafl, int[2] nquad, output int[nt3] colch, output int[nt3] rowch, output double[nt3] volch);
 */
const char* stubids3_ = "createbemdatastructmatlab(i int[xx], i int[x], i double[xx], i int[x], i double[x], i double[xx], i int[x], i int[x], i int[x], o double[x], o double[xx], i int[x], o int[x], o int[x], o double[x])";

void mexStub3(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int*        in0_ =0; /* t2p        */
    int*        in1_ =0; /* nt         */
    double*     in2_ =0; /* p          */
    int*        in3_ =0; /* np         */
    double*     in4_ =0; /* area       */
    double*     in5_ =0; /* normal     */
    int*        in6_ =0; /* row        */
    int*        in7_ =0; /* col        */
    int*        in8_ =0; /* ncols      */
    int*        in9_ =0; /* nquad      */
    double*     out0_=0; /* potout     */
    double*     out1_=0; /* triafl     */
    int*        out2_=0; /* colch      */
    int*        out3_=0; /* rowch      */
    double*     out4_=0; /* volch      */
    int         dim10_;   /* 3          */
    int         dim11_;   /* nt         */
    int         dim12_;   /* 1          */
    int         dim13_;   /* 3          */
    int         dim14_;   /* np         */
    int         dim15_;   /* 1          */
    int         dim16_;   /* nt         */
    int         dim17_;   /* 3          */
    int         dim18_;   /* nt         */
    int         dim19_;   /* ncols      */
    int         dim20_;   /* ncols      */
    int         dim21_;   /* 1          */
    int         dim22_;   /* ncols      */
    int         dim23_;   /* 3          */
    int         dim24_;   /* nt3        */
    int         dim25_;   /* 2          */
    int         dim26_;   /* nt3        */
    int         dim27_;   /* nt3        */
    int         dim28_;   /* nt3        */

    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (int) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (int) mxWrapGetScalar(prhs[16], &mw_err_txt_);
    dim17_ = (int) mxWrapGetScalar(prhs[17], &mw_err_txt_);
    dim18_ = (int) mxWrapGetScalar(prhs[18], &mw_err_txt_);
    dim19_ = (int) mxWrapGetScalar(prhs[19], &mw_err_txt_);
    dim20_ = (int) mxWrapGetScalar(prhs[20], &mw_err_txt_);
    dim21_ = (int) mxWrapGetScalar(prhs[21], &mw_err_txt_);
    dim22_ = (int) mxWrapGetScalar(prhs[22], &mw_err_txt_);
    dim23_ = (int) mxWrapGetScalar(prhs[23], &mw_err_txt_);
    dim24_ = (int) mxWrapGetScalar(prhs[24], &mw_err_txt_);
    dim25_ = (int) mxWrapGetScalar(prhs[25], &mw_err_txt_);
    dim26_ = (int) mxWrapGetScalar(prhs[26], &mw_err_txt_);
    dim27_ = (int) mxWrapGetScalar(prhs[27], &mw_err_txt_);
    dim28_ = (int) mxWrapGetScalar(prhs[28], &mw_err_txt_);

    if (mxGetM(prhs[0]) != dim10_ ||
        mxGetN(prhs[0]) != dim11_) {
        mw_err_txt_ = "Bad argument size: t2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != dim12_) {
        mw_err_txt_ = "Bad argument size: nt";        goto mw_err_label;
    }

    if (mxGetM(prhs[2]) != dim13_ ||
        mxGetN(prhs[2]) != dim14_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != dim15_) {
        mw_err_txt_ = "Bad argument size: np";        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim16_) {
        mw_err_txt_ = "Bad argument size: area";        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim17_ ||
        mxGetN(prhs[5]) != dim18_) {
        mw_err_txt_ = "Bad argument size: normal";
        goto mw_err_label;
    }

    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != dim19_) {
        mw_err_txt_ = "Bad argument size: row";        goto mw_err_label;
    }

    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != dim20_) {
        mw_err_txt_ = "Bad argument size: col";        goto mw_err_label;
    }

    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != dim21_) {
        mw_err_txt_ = "Bad argument size: ncols";        goto mw_err_label;
    }

    if (mxGetM(prhs[9])*mxGetN(prhs[9]) != dim25_) {
        mw_err_txt_ = "Bad argument size: nquad";        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxWrapGetArray_int(prhs[0], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in0_ = NULL;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxWrapGetArray_int(prhs[3], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxGetPr(prhs[4]);
    } else
        in4_ = NULL;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxGetPr(prhs[5]);
    } else
        in5_ = NULL;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxWrapGetArray_int(prhs[6], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in6_ = NULL;
    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != 0) {
        in7_ = mxWrapGetArray_int(prhs[7], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in7_ = NULL;
    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != 0) {
        in8_ = mxWrapGetArray_int(prhs[8], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in8_ = NULL;
    if (mxGetM(prhs[9])*mxGetN(prhs[9]) != 0) {
        in9_ = mxWrapGetArray_int(prhs[9], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in9_ = NULL;
    out0_ = (double*) mxMalloc(dim22_*sizeof(double));
    out1_ = (double*) mxMalloc(dim23_*dim24_*sizeof(double));
    out2_ = (int*) mxMalloc(dim26_*sizeof(int));
    out3_ = (int*) mxMalloc(dim27_*sizeof(int));
    out4_ = (double*) mxMalloc(dim28_*sizeof(double));
    if (mexprofrecord_)
        mexprofrecord_[3]++;
    MWF77_createbemdatastructmatlab(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, in8_, out0_, out1_, in9_, out2_, out3_, out4_);
    plhs[0] = mxCreateDoubleMatrix(dim22_, 1, mxREAL);
    mxWrapCopy_double(plhs[0], out0_, dim22_);
    plhs[1] = mxCreateDoubleMatrix(dim23_, dim24_, mxREAL);
    mxWrapCopy_double(plhs[1], out1_, dim23_*dim24_);
    plhs[2] = mxCreateDoubleMatrix(dim26_, 1, mxREAL);
    mxWrapCopy_int(plhs[2], out2_, dim26_);
    plhs[3] = mxCreateDoubleMatrix(dim27_, 1, mxREAL);
    mxWrapCopy_int(plhs[3], out3_, dim27_);
    plhs[4] = mxCreateDoubleMatrix(dim28_, 1, mxREAL);
    mxWrapCopy_double(plhs[4], out4_, dim28_);

mw_err_label:
    if (in0_)  mxFree(in0_);
    if (in1_)  mxFree(in1_);
    if (in3_)  mxFree(in3_);
    if (in6_)  mxFree(in6_);
    if (in7_)  mxFree(in7_);
    if (in8_)  mxFree(in8_);
    if (out0_) mxFree(out0_);
    if (out1_) mxFree(out1_);
    if (in9_)  mxFree(in9_);
    if (out2_) mxFree(out2_);
    if (out3_) mxFree(out3_);
    if (out4_) mxFree(out4_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 72 ----
 * computerhsmatlab(int[3, nt] t2p, int[1] nt, double[3, np] p, int[1] np, double[nt] epseff, double[3, nc] rs, double[3, nc] js, int[1] nc, int[2] iprec, output double[nt] rhs);
 */
const char* stubids4_ = "computerhsmatlab(i int[xx], i int[x], i double[xx], i int[x], i double[x], i double[xx], i double[xx], i int[x], i int[x], o double[x])";

void mexStub4(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int*        in0_ =0; /* t2p        */
    int*        in1_ =0; /* nt         */
    double*     in2_ =0; /* p          */
    int*        in3_ =0; /* np         */
    double*     in4_ =0; /* epseff     */
    double*     in5_ =0; /* rs         */
    double*     in6_ =0; /* js         */
    int*        in7_ =0; /* nc         */
    int*        in8_ =0; /* iprec      */
    double*     out0_=0; /* rhs        */
    int         dim9_;   /* 3          */
    int         dim10_;   /* nt         */
    int         dim11_;   /* 1          */
    int         dim12_;   /* 3          */
    int         dim13_;   /* np         */
    int         dim14_;   /* 1          */
    int         dim15_;   /* nt         */
    int         dim16_;   /* 3          */
    int         dim17_;   /* nc         */
    int         dim18_;   /* 3          */
    int         dim19_;   /* nc         */
    int         dim20_;   /* 1          */
    int         dim21_;   /* 2          */
    int         dim22_;   /* nt         */

    dim9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (int) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (int) mxWrapGetScalar(prhs[16], &mw_err_txt_);
    dim17_ = (int) mxWrapGetScalar(prhs[17], &mw_err_txt_);
    dim18_ = (int) mxWrapGetScalar(prhs[18], &mw_err_txt_);
    dim19_ = (int) mxWrapGetScalar(prhs[19], &mw_err_txt_);
    dim20_ = (int) mxWrapGetScalar(prhs[20], &mw_err_txt_);
    dim21_ = (int) mxWrapGetScalar(prhs[21], &mw_err_txt_);
    dim22_ = (int) mxWrapGetScalar(prhs[22], &mw_err_txt_);

    if (mxGetM(prhs[0]) != dim9_ ||
        mxGetN(prhs[0]) != dim10_) {
        mw_err_txt_ = "Bad argument size: t2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != dim11_) {
        mw_err_txt_ = "Bad argument size: nt";        goto mw_err_label;
    }

    if (mxGetM(prhs[2]) != dim12_ ||
        mxGetN(prhs[2]) != dim13_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != dim14_) {
        mw_err_txt_ = "Bad argument size: np";        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim15_) {
        mw_err_txt_ = "Bad argument size: epseff";        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim16_ ||
        mxGetN(prhs[5]) != dim17_) {
        mw_err_txt_ = "Bad argument size: rs";
        goto mw_err_label;
    }

    if (mxGetM(prhs[6]) != dim18_ ||
        mxGetN(prhs[6]) != dim19_) {
        mw_err_txt_ = "Bad argument size: js";
        goto mw_err_label;
    }

    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != dim20_) {
        mw_err_txt_ = "Bad argument size: nc";        goto mw_err_label;
    }

    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != dim21_) {
        mw_err_txt_ = "Bad argument size: iprec";        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxWrapGetArray_int(prhs[0], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in0_ = NULL;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxWrapGetArray_int(prhs[3], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxGetPr(prhs[4]);
    } else
        in4_ = NULL;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxGetPr(prhs[5]);
    } else
        in5_ = NULL;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxGetPr(prhs[6]);
    } else
        in6_ = NULL;
    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != 0) {
        in7_ = mxWrapGetArray_int(prhs[7], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in7_ = NULL;
    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != 0) {
        in8_ = mxWrapGetArray_int(prhs[8], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in8_ = NULL;
    out0_ = (double*) mxMalloc(dim22_*sizeof(double));
    if (mexprofrecord_)
        mexprofrecord_[4]++;
    MWF77_computerhsmatlab(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, in8_, out0_);
    plhs[0] = mxCreateDoubleMatrix(dim22_, 1, mxREAL);
    mxWrapCopy_double(plhs[0], out0_, dim22_);

mw_err_label:
    if (in0_)  mxFree(in0_);
    if (in1_)  mxFree(in1_);
    if (in3_)  mxFree(in3_);
    if (in7_)  mxFree(in7_);
    if (in8_)  mxFree(in8_);
    if (out0_) mxFree(out0_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 91 ----
 * fmmchargematlab(double[nfmm] chspace, double[3, nfmm] triafl, int[1] nfmm, output double[3, nfmm] fld, int[2] iprec);
 */
const char* stubids5_ = "fmmchargematlab(i double[x], i double[xx], i int[x], o double[xx], i int[x])";

void mexStub5(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double*     in0_ =0; /* chspace    */
    double*     in1_ =0; /* triafl     */
    int*        in2_ =0; /* nfmm       */
    int*        in3_ =0; /* iprec      */
    double*     out0_=0; /* fld        */
    int         dim4_;   /* nfmm       */
    int         dim5_;   /* 3          */
    int         dim6_;   /* nfmm       */
    int         dim7_;   /* 1          */
    int         dim8_;   /* 3          */
    int         dim9_;   /* nfmm       */
    int         dim10_;   /* 2          */

    dim4_ = (int) mxWrapGetScalar(prhs[4], &mw_err_txt_);
    dim5_ = (int) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    dim6_ = (int) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    dim7_ = (int) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (int) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != dim4_) {
        mw_err_txt_ = "Bad argument size: chspace";        goto mw_err_label;
    }

    if (mxGetM(prhs[1]) != dim5_ ||
        mxGetN(prhs[1]) != dim6_) {
        mw_err_txt_ = "Bad argument size: triafl";
        goto mw_err_label;
    }

    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != dim7_) {
        mw_err_txt_ = "Bad argument size: nfmm";        goto mw_err_label;
    }

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != dim10_) {
        mw_err_txt_ = "Bad argument size: iprec";        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxGetPr(prhs[0]);
    } else
        in0_ = NULL;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxGetPr(prhs[1]);
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxWrapGetArray_int(prhs[3], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in3_ = NULL;
    out0_ = (double*) mxMalloc(dim8_*dim9_*sizeof(double));
    if (mexprofrecord_)
        mexprofrecord_[5]++;
    MWF77_fmmchargematlab(in0_, in1_, in2_, out0_, in3_);
    plhs[0] = mxCreateDoubleMatrix(dim8_, dim9_, mxREAL);
    mxWrapCopy_double(plhs[0], out0_, dim8_*dim9_);

mw_err_label:
    if (in2_)  mxFree(in2_);
    if (out0_) mxFree(out0_);
    if (in3_)  mxFree(in3_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 143 ----
 * int nf = countfaces(int nte, int[4, nte] te2p, double[nte] condu, inout int[1] np2);
 */
const char* stubids6_ = "o int = countfaces(i int, i int[xx], i double[x], io int[x])";

void mexStub6(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int         in0_;    /* nte        */
    int*        in1_ =0; /* te2p       */
    double*     in2_ =0; /* condu      */
    int*        in3_ =0; /* np2        */
    int         out0_;   /* nf         */
    int         dim4_;   /* 4          */
    int         dim5_;   /* nte        */
    int         dim6_;   /* nte        */
    int         dim7_;   /* 1          */

    dim4_ = (int) mxWrapGetScalar(prhs[4], &mw_err_txt_);
    dim5_ = (int) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    dim6_ = (int) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    dim7_ = (int) mxWrapGetScalar(prhs[7], &mw_err_txt_);

    if (mxGetM(prhs[1]) != dim4_ ||
        mxGetN(prhs[1]) != dim5_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != dim6_) {
        mw_err_txt_ = "Bad argument size: condu";        goto mw_err_label;
    }

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != dim7_) {
        mw_err_txt_ = "Bad argument size: np2";        goto mw_err_label;
    }

    in0_ = (int) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxWrapGetArray_int(prhs[3], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in3_ = NULL;
    if (mexprofrecord_)
        mexprofrecord_[6]++;
    out0_ = countfaces(in0_, in1_, in2_, in3_);
    plhs[0] = mxCreateDoubleMatrix(1, 1, mxREAL);
    *mxGetPr(plhs[0]) = out0_;
    plhs[1] = mxCreateDoubleMatrix(dim7_, 1, mxREAL);
    mxWrapCopy_int(plhs[1], in3_, dim7_);

mw_err_label:
    if (in1_)  mxFree(in1_);
    if (in3_)  mxFree(in3_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 147 ----
 * makeBEMmesh(int nte, int[4, nte] te2p, double[3, np] p, double[nte] condu, inout int[3, nf] t2p, inout double[3, np2] p2, inout double[nf] epseff);
 */
const char* stubids7_ = "makeBEMmesh(i int, i int[xx], i double[xx], i double[x], io int[xx], io double[xx], io double[x])";

void mexStub7(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int         in0_;    /* nte        */
    int*        in1_ =0; /* te2p       */
    double*     in2_ =0; /* p          */
    double*     in3_ =0; /* condu      */
    int*        in4_ =0; /* t2p        */
    double*     in5_ =0; /* p2         */
    double*     in6_ =0; /* epseff     */
    int         dim7_;   /* 4          */
    int         dim8_;   /* nte        */
    int         dim9_;   /* 3          */
    int         dim10_;   /* np         */
    int         dim11_;   /* nte        */
    int         dim12_;   /* 3          */
    int         dim13_;   /* nf         */
    int         dim14_;   /* 3          */
    int         dim15_;   /* np2        */
    int         dim16_;   /* nf         */

    dim7_ = (int) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (int) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (int) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (int) mxWrapGetScalar(prhs[16], &mw_err_txt_);

    if (mxGetM(prhs[1]) != dim7_ ||
        mxGetN(prhs[1]) != dim8_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[2]) != dim9_ ||
        mxGetN(prhs[2]) != dim10_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != dim11_) {
        mw_err_txt_ = "Bad argument size: condu";        goto mw_err_label;
    }

    if (mxGetM(prhs[4]) != dim12_ ||
        mxGetN(prhs[4]) != dim13_) {
        mw_err_txt_ = "Bad argument size: t2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim14_ ||
        mxGetN(prhs[5]) != dim15_) {
        mw_err_txt_ = "Bad argument size: p2";
        goto mw_err_label;
    }

    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != dim16_) {
        mw_err_txt_ = "Bad argument size: epseff";        goto mw_err_label;
    }

    in0_ = (int) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxWrapGetArray_int(prhs[4], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in4_ = NULL;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_double(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxWrapGetArray_double(prhs[6], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in6_ = NULL;
    if (mexprofrecord_)
        mexprofrecord_[7]++;
    makeBEMmesh(in0_, in1_, in2_, in3_, in4_, in5_, in6_);
    plhs[0] = mxCreateDoubleMatrix(dim12_, dim13_, mxREAL);
    mxWrapCopy_int(plhs[0], in4_, dim12_*dim13_);
    plhs[1] = mxCreateDoubleMatrix(dim14_, dim15_, mxREAL);
    mxWrapCopy_double(plhs[1], in5_, dim14_*dim15_);
    plhs[2] = mxCreateDoubleMatrix(dim16_, 1, mxREAL);
    mxWrapCopy_double(plhs[2], in6_, dim16_);

mw_err_label:
    if (in1_)  mxFree(in1_);
    if (in4_)  mxFree(in4_);
    if (in5_)  mxFree(in5_);
    if (in6_)  mxFree(in6_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 173 ----
 * bemsolver(int[3, nt] t2p, int[1] nt, double[3, np] p, int[1] np, double[nt] reg, double[3, nc] rs, double[3, nc] js, int[1] nc, output double* xval, int[2] nquad, int[2] iprec, double[1] dnear, output int[1] iter, output double[1] relres);
 */
const char* stubids8_ = "bemsolver(i int[xx], i int[x], i double[xx], i int[x], i double[x], i double[xx], i double[xx], i int[x], o double*, i int[x], i int[x], i double[x], o int[x], o double[x])";

void mexStub8(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int*        in0_ =0; /* t2p        */
    int*        in1_ =0; /* nt         */
    double*     in2_ =0; /* p          */
    int*        in3_ =0; /* np         */
    double*     in4_ =0; /* reg        */
    double*     in5_ =0; /* rs         */
    double*     in6_ =0; /* js         */
    int*        in7_ =0; /* nc         */
    int*        in8_ =0; /* nquad      */
    int*        in9_ =0; /* iprec      */
    double*     in10_ =0; /* dnear      */
    double      out0_;   /* xval       */
    int*        out1_=0; /* iter       */
    double*     out2_=0; /* relres     */
    int         dim11_;   /* 3          */
    int         dim12_;   /* nt         */
    int         dim13_;   /* 1          */
    int         dim14_;   /* 3          */
    int         dim15_;   /* np         */
    int         dim16_;   /* 1          */
    int         dim17_;   /* nt         */
    int         dim18_;   /* 3          */
    int         dim19_;   /* nc         */
    int         dim20_;   /* 3          */
    int         dim21_;   /* nc         */
    int         dim22_;   /* 1          */
    int         dim23_;   /* 2          */
    int         dim24_;   /* 2          */
    int         dim25_;   /* 1          */
    int         dim26_;   /* 1          */
    int         dim27_;   /* 1          */

    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (int) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (int) mxWrapGetScalar(prhs[16], &mw_err_txt_);
    dim17_ = (int) mxWrapGetScalar(prhs[17], &mw_err_txt_);
    dim18_ = (int) mxWrapGetScalar(prhs[18], &mw_err_txt_);
    dim19_ = (int) mxWrapGetScalar(prhs[19], &mw_err_txt_);
    dim20_ = (int) mxWrapGetScalar(prhs[20], &mw_err_txt_);
    dim21_ = (int) mxWrapGetScalar(prhs[21], &mw_err_txt_);
    dim22_ = (int) mxWrapGetScalar(prhs[22], &mw_err_txt_);
    dim23_ = (int) mxWrapGetScalar(prhs[23], &mw_err_txt_);
    dim24_ = (int) mxWrapGetScalar(prhs[24], &mw_err_txt_);
    dim25_ = (int) mxWrapGetScalar(prhs[25], &mw_err_txt_);
    dim26_ = (int) mxWrapGetScalar(prhs[26], &mw_err_txt_);
    dim27_ = (int) mxWrapGetScalar(prhs[27], &mw_err_txt_);

    if (mxGetM(prhs[0]) != dim11_ ||
        mxGetN(prhs[0]) != dim12_) {
        mw_err_txt_ = "Bad argument size: t2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != dim13_) {
        mw_err_txt_ = "Bad argument size: nt";        goto mw_err_label;
    }

    if (mxGetM(prhs[2]) != dim14_ ||
        mxGetN(prhs[2]) != dim15_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != dim16_) {
        mw_err_txt_ = "Bad argument size: np";        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim17_) {
        mw_err_txt_ = "Bad argument size: reg";        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim18_ ||
        mxGetN(prhs[5]) != dim19_) {
        mw_err_txt_ = "Bad argument size: rs";
        goto mw_err_label;
    }

    if (mxGetM(prhs[6]) != dim20_ ||
        mxGetN(prhs[6]) != dim21_) {
        mw_err_txt_ = "Bad argument size: js";
        goto mw_err_label;
    }

    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != dim22_) {
        mw_err_txt_ = "Bad argument size: nc";        goto mw_err_label;
    }

    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != dim23_) {
        mw_err_txt_ = "Bad argument size: nquad";        goto mw_err_label;
    }

    if (mxGetM(prhs[9])*mxGetN(prhs[9]) != dim24_) {
        mw_err_txt_ = "Bad argument size: iprec";        goto mw_err_label;
    }

    if (mxGetM(prhs[10])*mxGetN(prhs[10]) != dim25_) {
        mw_err_txt_ = "Bad argument size: dnear";        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxWrapGetArray_int(prhs[0], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in0_ = NULL;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxWrapGetArray_int(prhs[3], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxGetPr(prhs[4]);
    } else
        in4_ = NULL;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxGetPr(prhs[5]);
    } else
        in5_ = NULL;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxGetPr(prhs[6]);
    } else
        in6_ = NULL;
    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != 0) {
        in7_ = mxWrapGetArray_int(prhs[7], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in7_ = NULL;
    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != 0) {
        in8_ = mxWrapGetArray_int(prhs[8], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in8_ = NULL;
    if (mxGetM(prhs[9])*mxGetN(prhs[9]) != 0) {
        in9_ = mxWrapGetArray_int(prhs[9], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in9_ = NULL;
    if (mxGetM(prhs[10])*mxGetN(prhs[10]) != 0) {
        in10_ = mxGetPr(prhs[10]);
    } else
        in10_ = NULL;
    out1_ = (int*) mxMalloc(dim26_*sizeof(int));
    out2_ = (double*) mxMalloc(dim27_*sizeof(double));
    if (mexprofrecord_)
        mexprofrecord_[8]++;
    MWF77_bemsolver(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, &out0_, in8_, in9_, in10_, out1_, out2_);
    plhs[0] = mxCreateDoubleMatrix(1, 1, mxREAL);
    *mxGetPr(plhs[0]) = out0_;
    plhs[1] = mxCreateDoubleMatrix(dim26_, 1, mxREAL);
    mxWrapCopy_int(plhs[1], out1_, dim26_);
    plhs[2] = mxCreateDoubleMatrix(dim27_, 1, mxREAL);
    mxWrapCopy_double(plhs[2], out2_, dim27_);

mw_err_label:
    if (in0_)  mxFree(in0_);
    if (in1_)  mxFree(in1_);
    if (in3_)  mxFree(in3_);
    if (in7_)  mxFree(in7_);
    if (in8_)  mxFree(in8_);
    if (in9_)  mxFree(in9_);
    if (out1_) mxFree(out1_);
    if (out2_) mxFree(out2_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- demo.mw: 206 ----
 * evaluateEfield(int[3, nt] t2p, int[1] nt, double[3, np] p, int[1] np, double[nt] reg, double[3, nc] rs, double[3, nc] js, int[1] nc, double[nt] xval, double[3, nobs] robs, int[1] nobs, inout double[3, nobs] Etotal, int[2] nquad, int[2] iprec, double[1] dnear);
 */
const char* stubids9_ = "evaluateEfield(i int[xx], i int[x], i double[xx], i int[x], i double[x], i double[xx], i double[xx], i int[x], i double[x], i double[xx], i int[x], io double[xx], i int[x], i int[x], i double[x])";

void mexStub9(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int*        in0_ =0; /* t2p        */
    int*        in1_ =0; /* nt         */
    double*     in2_ =0; /* p          */
    int*        in3_ =0; /* np         */
    double*     in4_ =0; /* reg        */
    double*     in5_ =0; /* rs         */
    double*     in6_ =0; /* js         */
    int*        in7_ =0; /* nc         */
    double*     in8_ =0; /* xval       */
    double*     in9_ =0; /* robs       */
    int*        in10_ =0; /* nobs       */
    double*     in11_ =0; /* Etotal     */
    int*        in12_ =0; /* nquad      */
    int*        in13_ =0; /* iprec      */
    double*     in14_ =0; /* dnear      */
    int         dim15_;   /* 3          */
    int         dim16_;   /* nt         */
    int         dim17_;   /* 1          */
    int         dim18_;   /* 3          */
    int         dim19_;   /* np         */
    int         dim20_;   /* 1          */
    int         dim21_;   /* nt         */
    int         dim22_;   /* 3          */
    int         dim23_;   /* nc         */
    int         dim24_;   /* 3          */
    int         dim25_;   /* nc         */
    int         dim26_;   /* 1          */
    int         dim27_;   /* nt         */
    int         dim28_;   /* 3          */
    int         dim29_;   /* nobs       */
    int         dim30_;   /* 1          */
    int         dim31_;   /* 3          */
    int         dim32_;   /* nobs       */
    int         dim33_;   /* 2          */
    int         dim34_;   /* 2          */
    int         dim35_;   /* 1          */

    dim15_ = (int) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (int) mxWrapGetScalar(prhs[16], &mw_err_txt_);
    dim17_ = (int) mxWrapGetScalar(prhs[17], &mw_err_txt_);
    dim18_ = (int) mxWrapGetScalar(prhs[18], &mw_err_txt_);
    dim19_ = (int) mxWrapGetScalar(prhs[19], &mw_err_txt_);
    dim20_ = (int) mxWrapGetScalar(prhs[20], &mw_err_txt_);
    dim21_ = (int) mxWrapGetScalar(prhs[21], &mw_err_txt_);
    dim22_ = (int) mxWrapGetScalar(prhs[22], &mw_err_txt_);
    dim23_ = (int) mxWrapGetScalar(prhs[23], &mw_err_txt_);
    dim24_ = (int) mxWrapGetScalar(prhs[24], &mw_err_txt_);
    dim25_ = (int) mxWrapGetScalar(prhs[25], &mw_err_txt_);
    dim26_ = (int) mxWrapGetScalar(prhs[26], &mw_err_txt_);
    dim27_ = (int) mxWrapGetScalar(prhs[27], &mw_err_txt_);
    dim28_ = (int) mxWrapGetScalar(prhs[28], &mw_err_txt_);
    dim29_ = (int) mxWrapGetScalar(prhs[29], &mw_err_txt_);
    dim30_ = (int) mxWrapGetScalar(prhs[30], &mw_err_txt_);
    dim31_ = (int) mxWrapGetScalar(prhs[31], &mw_err_txt_);
    dim32_ = (int) mxWrapGetScalar(prhs[32], &mw_err_txt_);
    dim33_ = (int) mxWrapGetScalar(prhs[33], &mw_err_txt_);
    dim34_ = (int) mxWrapGetScalar(prhs[34], &mw_err_txt_);
    dim35_ = (int) mxWrapGetScalar(prhs[35], &mw_err_txt_);

    if (mxGetM(prhs[0]) != dim15_ ||
        mxGetN(prhs[0]) != dim16_) {
        mw_err_txt_ = "Bad argument size: t2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != dim17_) {
        mw_err_txt_ = "Bad argument size: nt";        goto mw_err_label;
    }

    if (mxGetM(prhs[2]) != dim18_ ||
        mxGetN(prhs[2]) != dim19_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != dim20_) {
        mw_err_txt_ = "Bad argument size: np";        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim21_) {
        mw_err_txt_ = "Bad argument size: reg";        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim22_ ||
        mxGetN(prhs[5]) != dim23_) {
        mw_err_txt_ = "Bad argument size: rs";
        goto mw_err_label;
    }

    if (mxGetM(prhs[6]) != dim24_ ||
        mxGetN(prhs[6]) != dim25_) {
        mw_err_txt_ = "Bad argument size: js";
        goto mw_err_label;
    }

    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != dim26_) {
        mw_err_txt_ = "Bad argument size: nc";        goto mw_err_label;
    }

    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != dim27_) {
        mw_err_txt_ = "Bad argument size: xval";        goto mw_err_label;
    }

    if (mxGetM(prhs[9]) != dim28_ ||
        mxGetN(prhs[9]) != dim29_) {
        mw_err_txt_ = "Bad argument size: robs";
        goto mw_err_label;
    }

    if (mxGetM(prhs[10])*mxGetN(prhs[10]) != dim30_) {
        mw_err_txt_ = "Bad argument size: nobs";        goto mw_err_label;
    }

    if (mxGetM(prhs[11]) != dim31_ ||
        mxGetN(prhs[11]) != dim32_) {
        mw_err_txt_ = "Bad argument size: Etotal";
        goto mw_err_label;
    }

    if (mxGetM(prhs[12])*mxGetN(prhs[12]) != dim33_) {
        mw_err_txt_ = "Bad argument size: nquad";        goto mw_err_label;
    }

    if (mxGetM(prhs[13])*mxGetN(prhs[13]) != dim34_) {
        mw_err_txt_ = "Bad argument size: iprec";        goto mw_err_label;
    }

    if (mxGetM(prhs[14])*mxGetN(prhs[14]) != dim35_) {
        mw_err_txt_ = "Bad argument size: dnear";        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxWrapGetArray_int(prhs[0], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in0_ = NULL;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxWrapGetArray_int(prhs[3], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxGetPr(prhs[4]);
    } else
        in4_ = NULL;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxGetPr(prhs[5]);
    } else
        in5_ = NULL;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxGetPr(prhs[6]);
    } else
        in6_ = NULL;
    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != 0) {
        in7_ = mxWrapGetArray_int(prhs[7], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in7_ = NULL;
    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != 0) {
        in8_ = mxGetPr(prhs[8]);
    } else
        in8_ = NULL;
    if (mxGetM(prhs[9])*mxGetN(prhs[9]) != 0) {
        in9_ = mxGetPr(prhs[9]);
    } else
        in9_ = NULL;
    if (mxGetM(prhs[10])*mxGetN(prhs[10]) != 0) {
        in10_ = mxWrapGetArray_int(prhs[10], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in10_ = NULL;
    if (mxGetM(prhs[11])*mxGetN(prhs[11]) != 0) {
        in11_ = mxWrapGetArray_double(prhs[11], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in11_ = NULL;
    if (mxGetM(prhs[12])*mxGetN(prhs[12]) != 0) {
        in12_ = mxWrapGetArray_int(prhs[12], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in12_ = NULL;
    if (mxGetM(prhs[13])*mxGetN(prhs[13]) != 0) {
        in13_ = mxWrapGetArray_int(prhs[13], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in13_ = NULL;
    if (mxGetM(prhs[14])*mxGetN(prhs[14]) != 0) {
        in14_ = mxGetPr(prhs[14]);
    } else
        in14_ = NULL;
    if (mexprofrecord_)
        mexprofrecord_[9]++;
    MWF77_evaluateEfield(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, in8_, in9_, in10_, in11_, in12_, in13_, in14_);
    plhs[0] = mxCreateDoubleMatrix(dim31_, dim32_, mxREAL);
    mxWrapCopy_double(plhs[0], in11_, dim31_*dim32_);

mw_err_label:
    if (in0_)  mxFree(in0_);
    if (in1_)  mxFree(in1_);
    if (in3_)  mxFree(in3_);
    if (in7_)  mxFree(in7_);
    if (in10_)  mxFree(in10_);
    if (in11_)  mxFree(in11_);
    if (in12_)  mxFree(in12_);
    if (in13_)  mxFree(in13_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ----
 */
void mexFunction(int nlhs, mxArray* plhs[],
                 int nrhs, const mxArray* prhs[])
{
    char id[512];
    if (nrhs == 0) {
        mexPrintf("Mex function installed\n");
        return;
    }

    if (mxGetString(prhs[0], id, sizeof(id)) != 0)
        mexErrMsgTxt("Identifier should be a string");
    else if (strcmp(id, stubids1_) == 0)
        mexStub1(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids2_) == 0)
        mexStub2(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids3_) == 0)
        mexStub3(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids4_) == 0)
        mexStub4(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids5_) == 0)
        mexStub5(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids6_) == 0)
        mexStub6(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids7_) == 0)
        mexStub7(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids8_) == 0)
        mexStub8(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids9_) == 0)
        mexStub9(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, "*profile on*") == 0) {
        if (!mexprofrecord_) {
            mexprofrecord_ = (int*) malloc(10 * sizeof(int));
            mexLock();
        }
        memset(mexprofrecord_, 0, 10 * sizeof(int));
    } else if (strcmp(id, "*profile off*") == 0) {
        if (mexprofrecord_) {
            free(mexprofrecord_);
            mexUnlock();
        }
        mexprofrecord_ = NULL;
    } else if (strcmp(id, "*profile report*") == 0) {
        if (!mexprofrecord_)
            mexPrintf("Profiler inactive\n");
        mexPrintf("%d calls to demo.mw:54\n", mexprofrecord_[1]);
        mexPrintf("%d calls to demo.mw:56\n", mexprofrecord_[2]);
        mexPrintf("%d calls to demo.mw:61\n", mexprofrecord_[3]);
        mexPrintf("%d calls to demo.mw:72\n", mexprofrecord_[4]);
        mexPrintf("%d calls to demo.mw:91\n", mexprofrecord_[5]);
        mexPrintf("%d calls to demo.mw:143\n", mexprofrecord_[6]);
        mexPrintf("%d calls to demo.mw:147\n", mexprofrecord_[7]);
        mexPrintf("%d calls to demo.mw:173\n", mexprofrecord_[8]);
        mexPrintf("%d calls to demo.mw:206\n", mexprofrecord_[9]);
    } else if (strcmp(id, "*profile log*") == 0) {
        FILE* logfp;
        if (nrhs != 2 || mxGetString(prhs[1], id, sizeof(id)) != 0)
            mexErrMsgTxt("Must have two string arguments");
        logfp = fopen(id, "w+");
        if (!logfp)
            mexErrMsgTxt("Cannot open log for output");
        if (!mexprofrecord_)
            fprintf(logfp, "Profiler inactive\n");
        fprintf(logfp, "%d calls to demo.mw:54\n", mexprofrecord_[1]);
        fprintf(logfp, "%d calls to demo.mw:56\n", mexprofrecord_[2]);
        fprintf(logfp, "%d calls to demo.mw:61\n", mexprofrecord_[3]);
        fprintf(logfp, "%d calls to demo.mw:72\n", mexprofrecord_[4]);
        fprintf(logfp, "%d calls to demo.mw:91\n", mexprofrecord_[5]);
        fprintf(logfp, "%d calls to demo.mw:143\n", mexprofrecord_[6]);
        fprintf(logfp, "%d calls to demo.mw:147\n", mexprofrecord_[7]);
        fprintf(logfp, "%d calls to demo.mw:173\n", mexprofrecord_[8]);
        fprintf(logfp, "%d calls to demo.mw:206\n", mexprofrecord_[9]);
        fclose(logfp);
    } else
        mexErrMsgTxt("Unknown identifier");
}

